trigger: none

parameters:
- name: api_project
  displayName: Deploy which API project?
  type: string
  values:
  # - number_conversion
  - ping
  - odata_tutorial
  # - star_wars
  - petstore
  - petstore_basicauth
  - petstore_versioning
  - postman_echo
  # - postman_echo_jwt
  # - postman_echo_oauth2
  - postman_mocking
  - multiple_tenants
  - security_alias
  - 'other (Please specify below)'
- name: api_project_other
  displayName: Deploy which other API project?
  type: string
  default: 'n/a'

variables:
- template: /variables/variables-aliases-template.yml
# - template: /variables/variables-artifactory-template.yml
- group: 'Project Configuration'

name: $(Date:yyyyMMdd).$(Rev:r)-${{parameters.api_project}}

stages:
- template: /pipelines/api-build-and-deploy-stages-template.yml
  parameters:
    target_stages:
    - name: DESIGN
      instances:
      - DESIGN
    deployment_sets:
    - api_projects:
      - ${{ if ne(parameters.api_project, 'other (Please specify below)') }}:
        - ${{parameters.api_project}}
      - ${{ else }}:
        - ${{parameters.api_project_other}}
      targets:
      - DESIGN