trigger: none

resources:
  pipelines:
  - pipeline: trigger-pipeline # Name of the pipeline resource.
    source: 'Configure API Gateways' # The name of the pipeline referenced by this pipeline resource.
    trigger: true

variables:
- template: /variables/variables-aliases-template.yml
# - template: /variables/variables-artifactory-template.yml
- group: 'Project Configuration'

stages:
- template: /pipelines/api-inject-stages-template.yml
  parameters:
    template: /pipelines/api-build-and-deploy-stages-template.yml
    parameters:
      deployment_sets:
      - api_projects:
        # - number_conversion
        - ping
        - odata_tutorial
        # - star_wars
        targets:
        - DEV_INT
        - DEV_EXT
        - TEST_INT
        - TEST_EXT
        - PROD_INT
        - PROD_EXT

      - api_projects:
        - petstore
        # - petstore_basicauth
        - petstore_versioning
        targets:
        - DEV_INT
        - TEST_INT
        - PROD_INT

      - api_projects:
        - postman_echo
        # - postman_echo_jwt
        # - postman_echo_oauth2
        - postman_mocking
        # - multiple_tenants
        - security_alias
        targets:
        - DEV_EXT
        - TEST_EXT
        - PROD_EXT