trigger: none
  # branches:
  #   include:
  #   - azure-demo

resources:
  pipelines:
  - pipeline: trigger-pipeline # Name of the pipeline resource.
    source: 'Configure API Gateways' # The name of the pipeline referenced by this pipeline resource.
    trigger:
      tags:
      - DESIGN

variables:
- template: /variables/variables-aliases-template.yml
# - template: /variables/variables-artifactory-template.yml
- group: 'Project Configuration'

# name: $(Date:yyyyMMdd).$(Rev:r)-${{parameters.api_project}}

stages:
- template: /pipelines/api-inject-stages-template.yml
  parameters:
    template: /pipelines/api-build-and-deploy-stages-template.yml
    parameters:
      deployment_sets:
      - api_projects:
        # - number_conversion
        - odata_tutorial
        - ping
        # - star_wars
        - petstore
        - petstore_basicauth
        - petstore_versioning
        - postman_echo
        # - postman_echo_jwt
        # - postman_echo_oauth2
        - postman_mocking
        - multiple_tenants
        - security_alias
        targets:
        - DESIGN