parameters:
- name: design_stage
  type: object
- name: build_stage
  type: object
- name: target_stages
  type: object
- name: all_stages
  type: object
- name: build_instances_mapping
  type: object
- name: environment_set
- name: deployment_sets
  type: object

stages:
- ${{ each stage in parameters.all_stages }}:
  - stage: Configure_${{stage.name}}
    dependsOn: []
    jobs:
    - ${{ each instance in stage.instances }}:
      - deployment: Configure_API_Gateway_${{instance.name}}
        environment: API_Gateway_${{instance.name}}
        variables:
        - group: ${{stage.name}}_users
        - group: ${{instance.name}}_users
        pool:
          name: ${{instance.pool_name}}
          vmImage: ${{instance.pool_image}}
        strategy:
          runOnce:    #rolling, canary are the other strategies that are supported
            deploy:
              steps:
              - checkout: self
                submodules: "true"
                persistCredentials: "true"
                fetchDepth: 0
              - download: none
              # - bash: "Debug: $[dependencies.Check_environment_file_for_${{instance.name}}.outputs['Check_environment_file.environment_file_exists']]"
              - template: /pipelines/step-templates/configure-api-gateway.yml
                parameters:
                  environment_set: ${{parameters.environment_set}}
                  stage_name: ${{stage.name}}
                  instance_name: ${{instance.name}}
                  environment: API_Gateway_${{instance.name}}_environment.json
              - bash: |
                  echo "##vso[build.addbuildtag]${{parameters.environment_set}}"
                  echo "##vso[build.addbuildtag]${{stage.name}}"
                  echo "##vso[build.addbuildtag]${{instance.name}}"
                displayName: Add build tags

    - ${{ if stage.configure_haft }}: # Configure HAFT on PROD stages
      - ${{ each instance in stage.instances }}:
        - deployment: Configure_HAFT_listener_for_API_Gateway_${{instance.name}}
          dependsOn: Configure_API_Gateway_${{instance.name}}
          environment: API_Gateway_${{instance.name}}
          variables:
          - group: ${{instance.name}}_users
          pool:
            name: ${{instance.pool_name}}
            vmImage: ${{instance.pool_image}}
          strategy:
            runOnce:    #rolling, canary are the other strategies that are supported
              deploy:
                steps:
                - checkout: self
                  submodules: "true"
                  persistCredentials: "true"
                  fetchDepth: 0
                - download: none
                - template: /pipelines/step-templates/configure-haft-listener.yml
                  parameters:
                    environment_set: ${{parameters.environment_set}}
                    stage_name: ${{stage.name}}
                    instance_name: ${{instance.name}}
                    environment: API_Gateway_${{instance.name}}_environment.json

        - deployment: Configure_HAFT_ring_for_API_Gateway_${{instance.name}}
          dependsOn:
          - ${{ each otherinstance in stage.instances }}:
            - Configure_HAFT_listener_for_API_Gateway_${{otherinstance.name}}
          environment: API_Gateway_${{instance.name}}
          variables:
          - group: ${{instance.name}}_users
          - name: node_name_01
            value: $[dependencies.Configure_HAFT_listener_for_API_Gateway_${{ stage.instances[0].name }}.outputs['Configure_HAFT_listener_for_API_Gateway_${{ stage.instances[0].name }}.setoutputvar.node_name']]
          - name: node_name_02
            value: $[dependencies.Configure_HAFT_listener_for_API_Gateway_${{ stage.instances[1].name }}.outputs['Configure_HAFT_listener_for_API_Gateway_${{ stage.instances[1].name }}.setoutputvar.node_name']]
          pool:
            name: ${{instance.pool_name}}
            vmImage: ${{instance.pool_image}}
          strategy:
            runOnce:    #rolling, canary are the other strategies that are supported
              deploy:
                steps:
                - checkout: self
                  submodules: "true"
                  persistCredentials: "true"
                  fetchDepth: 0
                - download: none
                - template: /pipelines/step-templates/configure-haft-ring.yml
                  parameters:
                    environment_set: ${{parameters.environment_set}}
                    stage_name: ${{stage.name}}
                    instance_name: ${{instance.name}}
                    environment: API_Gateway_${{instance.name}}_environment.json

      - job: Wait_for_HAFT_ring_on_${{stage.name}}
        pool: server # note: the value 'server' is a reserved keyword which indicates this is an agentless job
        dependsOn:
        - ${{ each otherinstance in stage.instances }}:
          - Configure_HAFT_ring_for_API_Gateway_${{otherinstance.name}}
        steps:
        - task: Delay@1
          inputs:
            delayForMinutes: '5'

      - ${{ each instance in stage.instances }}:
        - deployment: Validate_HAFT_ring_for_API_Gateway_${{instance.name}}
          dependsOn: Wait_for_HAFT_ring_on_${{stage.name}}
          environment: API_Gateway_${{instance.name}}
          variables:
          - group: ${{instance.name}}_users
          pool:
            name: ${{instance.pool_name}}
            vmImage: ${{instance.pool_image}}
          strategy:
            runOnce:    #rolling, canary are the other strategies that are supported
              deploy:
                steps:
                - checkout: self
                  submodules: "true"
                  persistCredentials: "true"
                  fetchDepth: 0
                - download: none
                - template: /pipelines/step-templates/configure-haft-ring-validation.yml
                  parameters:
                    environment_set: ${{parameters.environment_set}}
                    stage_name: ${{stage.name}}
                    instance_name: ${{instance.name}}
                    environment: API_Gateway_${{instance.name}}_environment.json
                - bash: | 
                    echo "##vso[build.addbuildtag]${{stage.name}}_HAFT"
                    echo "##vso[build.addbuildtag]${{instance.name}}_HAFT"
                  displayName: Add build tag