parameters:
- name: design_stage
  type: object
- name: build_stage
  type: object
- name: target_stages
  type: object
- name: all_stages
  type: object
- name: build_environments_mapping
  type: object
- name: build_job_assignment_mechanism
  type: string
- name: environment_set
  type: string
- name: deployment_sets
  type: object

- name: source_environment
  type: string
- name: commit_message
  type: string

stages:
- ${{ each stage in parameters.all_stages }}:
  - ${{ each environment in stage.environments }}:
    - ${{ if eq(environment.name, parameters.source_environment) }}:
      - stage: Export_from_${{stage.name}}
        dependsOn: []
        jobs:
        - deployment: Export_config_from_API_Gateway_${{environment.name}}
          environment: API_Gateway_${{parameters.environment_set}}_${{environment.name}}
          variables:
          - group: API_Gateway_${{parameters.environment_set}}_${{stage.name}}_users
          - group: API_Gateway_${{parameters.environment_set}}_${{environment.name}}_users
          pool:
            name: ${{environment.pool_name}}
            vmImage: ${{environment.pool_image}}
          strategy:
            runOnce:    #rolling, canary are the other strategies that are supported
              deploy:
                steps:
                - checkout: self
                  submodules: "true"
                  persistCredentials: "true"
                  fetchDepth: 0
                - template: /pipelines/step-templates/export-config.yml
                  parameters:
                    environment_set: ${{parameters.environment_set}}
                    environment_file: API_Gateway_${{environment.name}}_environment.json
                    stage_name: ${{stage.name}}
                    environment_name: ${{environment.name}}
                - template: /pipelines/step-templates/commit.yml
                  parameters:
                    commit_message: ${{parameters.commit_message}}
                - bash: |
                    echo "##vso[build.addbuildtag]${{parameters.environment_set}}"
                    echo "##vso[build.addbuildtag]${{stage.name}}"
                    echo "##vso[build.addbuildtag]${{environment.name}}"
                  displayName: Add build tags