parameters:
- name: design_stage
  type: object
- name: build_stage
  type: object
- name: target_stages
  type: object
- name: all_stages
  type: object
- name: build_environments_mapping
  type: object
- name: build_job_assignment_mechanism
  type: string
- name: environment_set
  type: string
- name: deployment_sets
  type: object
- name: agwassets_repo_path
  type: string
- name: agwassets_repo_branchname
  type: string

- name: selected_api_project
  type: string
- name: commit_message
  type: string

stages:
- stage: Export_${{parameters.selected_api_project}}_from_${{parameters.design_stage.name}}
  jobs:
  - ${{ each environment in parameters.design_stage.environments }}: # Iterate over all DESIGN environments -> probably not what you want if you have multiple DESIGN environments?
    - deployment: Export_${{parameters.selected_api_project}}_from_API_Gateway_${{environment.name}}
      environment: API_Gateway_${{parameters.environment_set}}_${{environment.name}}
      variables:
      - group: API_Gateway_${{parameters.environment_set}}_users
      - group: API_Gateway_${{parameters.environment_set}}_${{parameters.design_stage.name}}_users
      - group: API_Gateway_${{parameters.environment_set}}_${{environment.name}}_users
      pool:
        name: ${{environment.pool_name}}
        vmImage: ${{environment.pool_image}}
      strategy:
        runOnce:    #rolling, canary are the other strategies that are supported
          deploy:
            steps:
            - template: /pipelines/checkout-multi-template.yml
              parameters:
                agwassets_repo_path: ${{parameters.agwassets_repo_path}} 
                agwassets_repo_branchname: ${{parameters.agwassets_repo_branchname}} 
            - download: none
            - bash: |
                ls -lrt $(Agent.BuildDirectory)
                ls -lrt $(Agent.BuildDirectory)/s
                ls -lrt $(Agent.BuildDirectory)/s/webmethods-api-gateway-staging/apis
                ls -lrt $(Agent.BuildDirectory)/APIGWASSETS_REPO/assets/apigateway/apiprojects
                cat $(Agent.BuildDirectory)/APIGWASSETS_REPO/assets/apigateway/apiprojects/${{parameters.selected_api_project}}/export_payload.json

            - template: /pipelines/step-templates/export-api.yml
              parameters:
                environment_set: ${{parameters.environment_set}}
                api_project: ${{parameters.selected_api_project}}
                environment_file: API_Gateway_${{environment.name}}_environment.json
                stage_name: ${{parameters.design_stage.name}}
                environment_name: ${{environment.name}}
            - template: /pipelines/step-templates/commit.yml
              parameters:
                commit_message: ${{parameters.commit_message}}
            - bash: |
                echo "##vso[build.addbuildtag]${{parameters.environment_set}}"
                echo "##vso[build.addbuildtag]${{parameters.selected_api_project}}"
                echo "##vso[build.addbuildtag]${{parameters.design_stage.name}}"
                echo "##vso[build.addbuildtag]${{environment.name}}"
                echo "##vso[build.addbuildtag]${{parameters.selected_api_project}}_${{parameters.design_stage.name}}"
                echo "##vso[build.addbuildtag]${{parameters.selected_api_project}}_${{environment.name}}"
              displayName: Add build tags
