parameters:
- name: template
  type: string
- name: parameters
  type: object
- name: api_project
  default: All
- name: environment_set
- name: selected_target
  default: 'All (including DESIGN)'
- name: selected_stage
  default: 'All'
- name: selected_build_environment
  type: string
  default: 'Default Mapping'
- name: ignore_eligible_targets
  type: string
  default: false
- name: stages
  type: object
  default:
  - name: DESIGN
    pool_name: vmsspoolagents-04
    pool_image: ubuntu-latest
    is_design_stage: true
    environments:
    - name: DESIGN
      pool_name: vmsspoolagents-04
      pool_image: ubuntu-latest
  - name: BUILD
    pool_name: vmsspoolagents-04
    pool_image: ubuntu-latest
    dedicated_pool_name: vmsspoolagents-build
    dedicated_pool_image: ubuntu-latest
    is_build_stage: true
    environments:
    - name: BUILD_01
      pool_name: vmsspoolagents-04
      pool_image: ubuntu-latest
    - name: BUILD_02
      pool_name: vmsspoolagents-04
      pool_image: ubuntu-latest
    - name: BUILD_03
      pool_name: vmsspoolagents-04
      pool_image: ubuntu-latest
    - name: BUILD_04
      pool_name: vmsspoolagents-04
      pool_image: ubuntu-latest
    - name: BUILD_05
      pool_name: vmsspoolagents-04
      pool_image: ubuntu-latest
    - name: BUILD_06
      pool_name: vmsspoolagents-04
      pool_image: ubuntu-latest
    - name: BUILD_07
      pool_name: vmsspoolagents-04
      pool_image: ubuntu-latest
  - name: DEV_INT
    pool_name: vmsspoolagents-04
    pool_image: ubuntu-latest
    environments:
    - name: DEV_INT
      pool_name: vmsspoolagents-04
      pool_image: ubuntu-latest
  - name: DEV_EXT
    pool_name: vmsspoolagents-04
    pool_image: ubuntu-latest
    environments:
    - name: DEV_EXT
      pool_name: vmsspoolagents-04
      pool_image: ubuntu-latest
  - name: TEST_INT
    pool_name: vmsspoolagents-04
    pool_image: ubuntu-latest
    environments:
    - name: TEST_INT
      pool_name: vmsspoolagents-04
      pool_image: ubuntu-latest
  - name: TEST_EXT
    pool_name: vmsspoolagents-04
    pool_image: ubuntu-latest
    environments:
    - name: TEST_EXT
      pool_name: vmsspoolagents-04
      pool_image: ubuntu-latest
  - name: PROD_INT
    pool_name: vmsspoolagents-04
    pool_image: ubuntu-latest
    configure_haft: true
    environments:
    - name: PROD_INT_01
      pool_name: vmsspoolagents-04
      pool_image: ubuntu-latest
    - name: PROD_INT_02
      pool_name: vmsspoolagents-04
      pool_image: ubuntu-latest
  - name: PROD_EXT
    pool_name: vmsspoolagents-04
    pool_image: ubuntu-latest
    configure_haft: true
    environments:
    - name: PROD_EXT_01
      pool_name: vmsspoolagents-04
      pool_image: ubuntu-latest
    - name: PROD_EXT_02
      pool_name: vmsspoolagents-04
      pool_image: ubuntu-latest
- name: build_environments_mapping
  type: object
  default:
    DESIGN: BUILD_01
    DEV_INT: BUILD_02
    DEV_EXT: BUILD_03
    TEST_INT: BUILD_04
    TEST_EXT: BUILD_05
    PROD_INT: BUILD_06
    PROD_EXT: BUILD_07
- name: ignore_selected_build_environment
  type: string
  default: false
- name: eligible_targets
  displayName: Which sets of API projects can be deployed on which API Gateway stages?
  type: object
  default:
  - api_projects:
    - number_conversion
    - ping
    - odata_tutorial
    - countries
    targets:
    - DEV_INT
    - DEV_EXT
    - TEST_INT
    - TEST_EXT
    - PROD_INT
    - PROD_EXT
  - api_projects:
    - petstore
    - petstore_basicauth
    - petstore_versioning
    targets:
    - DEV_INT
    - TEST_INT
    - PROD_INT
  - api_projects:
    - postman_echo
    - postman_echo_jwt
    - postman_echo_oauth2
    - postman_echo_mocking
    - postman_echo_multiple_tenants
    - postman_echo_security_alias
    targets:
    - DEV_EXT
    - TEST_EXT
    - PROD_EXT
  - api_projects:
    - number_conversion
    - odata_tutorial
    - ping
    - countries
    - petstore
    - petstore_basicauth
    - petstore_versioning
    - postman_echo
    - postman_echo_jwt
    - postman_echo_oauth2
    - postman_echo_mocking
    - postman_echo_multiple_tenants
    - postman_echo_security_alias
    targets:
    - DESIGN

stages:
- template: ${{parameters.template}}
  parameters:
    ${{ each stage in parameters.stages }}:
      ${{ if stage.is_design_stage }}:
        design_stage: ${{stage}}
      ${{ if stage.is_build_stage }}:
        build_stage: ${{stage}}
    target_stages:
    - ${{ each stage in parameters.stages }}:
      - ${{ if not(stage.is_build_stage) }}:
        - ${{stage}}
    all_stages:
    - ${{ each stage in parameters.stages }}:
      - ${{ if eq(parameters.selected_stage, stage.name) }}:
        - ${{stage}}
      - ${{ elseif eq(parameters.selected_stage, 'All') }}:
        - ${{stage}}
    ${{ if or(eq(parameters.ignore_selected_build_environment, 'true'), eq(parameters.selected_build_environment, 'Default Mapping') }}:
      build_environments_mapping: ${{parameters.build_environments_mapping}}
    ${{ else }}:
      build_environments_mapping:
        DESIGN: ${{parameters.build_environment}}
        DEV_INT: ${{parameters.build_environment}}
        DEV_EXT: ${{parameters.build_environment}}
        TEST_INT: ${{parameters.build_environment}}
        TEST_EXT: ${{parameters.build_environment}}
        PROD_INT: ${{parameters.build_environment}}
        PROD_EXT: ${{parameters.build_environment}}
    environment_set: ${{parameters.environment_set}}
    deployment_sets:
    - ${{ if eq(parameters.ignore_eligible_targets, 'true') }}:
      - api_projects:
        - ${{parameters.api_project}}
        targets:
        - ${{ each stage in parameters.stages }}:
          - ${{ if not(stage.is_build_stage) }}:
            - ${{ if eq(parameters.selected_target, stage.name) }}:
              - ${{stage.name}}
            - ${{ elseif eq(parameters.selected_target, 'All (including DESIGN)') }}:
              - ${{stage.name}}
            - ${{ elseif and(eq(parameters.selected_target, 'All (execpt DESIGN)'), ne(stage.name, 'DESIGN')) }}:
              - ${{stage.name}}
    - ${{ else }}:
      - ${{ each eligible_target in parameters.eligible_targets }}:
        - api_projects:
          - ${{ each api_project in eligible_target.api_projects }}:
            - ${{ if eq(parameters.api_project, api_project) }}:
              - ${{api_project}}
            - ${{ elseif eq(parameters.api_project, 'All') }}:
              - ${{api_project}}
          targets:
          - ${{ each target in eligible_target.targets }}:
            - ${{ if eq(parameters.selected_target, target) }}:
              - ${{target}}
            - ${{ elseif eq(parameters.selected_target, 'All (including DESIGN)') }}:
              - ${{target}}
            - ${{ elseif and(eq(parameters.selected_target, 'All (execpt DESIGN)'), ne(target, 'DESIGN')) }}:
              - ${{target}}
    ${{ each parameter in parameters.parameters}}:
      ${{parameter.key}}: ${{parameter.value}}