parameters:
- name: design_stage
  type: object
- name: build_stage
  type: object
- name: target_stages
  type: object
- name: all_stages
  type: object
- name: build_environments_mapping
  type: object
- name: environment_set
- name: deployment_sets
  type: object

stages:
- ${{ each stage in parameters.all_stages }}:
  - stage: Purge_Data_on_${{stage.name}}
    dependsOn: []
    jobs:
    - ${{ each environment in stage.environments }}:
      - deployment: Purge_Data_on_API_Gateway_${{environment.name}}
        environment: API_Gateway_${{parameters.environment_set}}_${{environment.name}}
        variables:
        - group: API_Gateway_${{parameters.environment_set}}_${{stage.name}}_users
        - group: API_Gateway_${{parameters.environment_set}}_${{environment.name}}_users
        pool:
          name: ${{environment.pool_name}}
          vmImage: ${{environment.pool_image}}
        strategy:
          runOnce:    #rolling, canary are the other strategies that are supported
            deploy:
              steps:
              - checkout: self
                submodules: "true"
                persistCredentials: "true"
                fetchDepth: 0
              - download: none
              - template: /pipelines/step-templates/purge-data.yml
                parameters:
                  environment_set: ${{parameters.environment_set}}
                  environment_name: ${{environment.name}}
                  environment_file: API_Gateway_${{environment.name}}_environment.json
              - bash: |
                  echo "##vso[build.addbuildtag]${{parameters.environment_set}}"
                  echo "##vso[build.addbuildtag]${{stage.name}}"
                  echo "##vso[build.addbuildtag]${{environment.name}}"
                displayName: Add build tags