trigger: none

resources:
  pipelines:
  - pipeline: trigger-pipeline # Name of the pipeline resource.
    source: 'Configure API Gateways' # The name of the pipeline referenced by this pipeline resource.
    trigger: true

parameters:
- name: DEV_INT_build_instance
  displayName: Build for DEV_INT on which BUILD instance?
  default: BUILD_01
  values:
  - BUILD_01
  - BUILD_02
  - BUILD_03
  - BUILD_04
  - BUILD_05
  - BUILD_06
  - BUILD_07
- name: DEV_EXT_build_instance
  displayName: Build for DEV_EXT on which BUILD instance?
  default: BUILD_02
  values:
  - BUILD_01
  - BUILD_02
  - BUILD_03
  - BUILD_04
  - BUILD_05
  - BUILD_06
  - BUILD_07
- name: TEST_INT_build_instance
  displayName: Build for TEST_INT on which BUILD instance?
  default: BUILD_03
  values:
  - BUILD_01
  - BUILD_02
  - BUILD_03
  - BUILD_04
  - BUILD_05
  - BUILD_06
  - BUILD_07
- name: TEST_EXT_build_instance
  displayName: Build for TEST_EXT on which BUILD instance?
  default: BUILD_04
  values:
  - BUILD_01
  - BUILD_02
  - BUILD_03
  - BUILD_04
  - BUILD_05
  - BUILD_06
  - BUILD_07
- name: PROD_INT_build_instance
  displayName: Build for PROD_INT on which BUILD instance?
  default: BUILD_05
  values:
  - BUILD_01
  - BUILD_02
  - BUILD_03
  - BUILD_04
  - BUILD_05
  - BUILD_06
  - BUILD_07
- name: PROD_EXT_build_instance
  displayName: Build for PROD_EXT on which BUILD instance?
  default: BUILD_06
  values:
  - BUILD_01
  - BUILD_02
  - BUILD_03
  - BUILD_04
  - BUILD_05
  - BUILD_06
  - BUILD_07

variables:
- group: Project_configuration

stages:
- template: /pipelines/api-inject-stages-template.yml
  parameters:
    template: /pipelines/api-build-and-deploy-stages-template.yml
    parameters:
      build_instances:
        DEV_INT: ${{parameters.DEV_INT_build_instance}}
        DEV_EXT: ${{parameters.DEV_EXT_build_instance}}
        TEST_INT: ${{parameters.TEST_INT_build_instance}}
        TEST_EXT: ${{parameters.TEST_EXT_build_instance}}
        PROD_INT: ${{parameters.PROD_INT_build_instance}}
        PROD_EXT: ${{parameters.PROD_EXT_build_instance}}
      deployment_sets:
      - api_projects:
        # - number_conversion
        - ping
        - odata_tutorial
        # - star_wars
        targets:
        - DEV_INT
        - DEV_EXT
        - TEST_INT
        - TEST_EXT
        - PROD_INT
        - PROD_EXT

      - api_projects:
        - petstore
        # - petstore_basicauth
        - petstore_versioning
        targets:
        - DEV_INT
        - TEST_INT
        - PROD_INT

      - api_projects:
        - postman_echo
        # - postman_echo_jwt
        # - postman_echo_oauth2
        - postman_mocking
        # - multiple_tenants
        - security_alias
        targets:
        - DEV_EXT
        - TEST_EXT
        - PROD_EXT