trigger: none

resources:
  pipelines:
  - pipeline: trigger-pipeline # Name of the pipeline resource.
    source: 'Configure API Gateways' # The name of the pipeline referenced by this pipeline resource.
    trigger:
      tags:
      - DESIGN

parameters:
- name: DESIGN_build_instance
  displayName: Build on which BUILD instance?
  default: BUILD_07
  values:
  - BUILD_01
  - BUILD_02
  - BUILD_03
  - BUILD_04
  - BUILD_05
  - BUILD_06
  - BUILD_07

variables:
- template: /variables/variables-aliases-template.yml
# - template: /variables/variables-artifactory-template.yml
- group: 'Project Configuration'

stages:
- template: /pipelines/api-inject-stages-template.yml
  parameters:
    template: /pipelines/api-build-and-deploy-stages-template.yml
    parameters:
      build_instances:
        DESIGN: ${{parameters.DESIGN_build_instance}}
      deployment_sets:
      - api_projects:
        # - number_conversion
        - odata_tutorial
        - ping
        # - star_wars
        - petstore
        - petstore_basicauth
        - petstore_versioning
        - postman_echo
        # - postman_echo_jwt
        # - postman_echo_oauth2
        - postman_mocking
        - multiple_tenants
        - security_alias
        targets:
        - DESIGN