# Pipeline for apig staging

trigger: none
  # branches:
  #   include:
  #   - azure-demo

parameters:
- name: tenant
  displayName: Configure API Gateway in which tenant?
  type: string
  default: playground
  values:
  - playground
  - realworld

stages:
- template: /pipelines/api-configure-stages-template.yml
  parameters:
    tenant: ${{parameters.tenant}}
    apiProjects:
    # - number_conversion
    - odata_tutorial
    - ping
    # - star_wars
    - petstore
    - petstore_basicauth
    - petstore_versioning
    - postman_echo
    # - postman_echo_jwt
    # - postman_echo_oauth2
    - postman_mocking
    - multiple_tenants
    - security_alias
    stages:
    - name: CONFIG
      jobs:
      - name: CONFIG
        pool: vmsspoolagents
        image: ubuntu-latest
    - name: BUILD
      buildjobs:
      - name: BUILD_01
        pool: buildagents
        image: ubuntu-latest
      - name: BUILD_02
        pool: buildagents
        image: ubuntu-latest
      - name: BUILD_03
        pool: buildagents
        image: ubuntu-latest