parameters:
- name: api_project
  type: string
- name: api_id
  type: string
- name: update_url
  type: string

stages:
# - template: /pipelines/api-inject-stages-template.yml
#   parameters:
#     template: /pipelines/api-build-and-deploy-stages-template.yml
#     parameters:
#       deployment_sets:
#       - api_projects:
#         - ${{parameters.api_project}}
#         targets:
#         - DESIGN
#     build_instance: BUILD_01

- stage: Update_${{parameters.api_project}}_on_DESIGN
  jobs:
  - deployment: Update_API_on_API_Gateway_DESIGN
    environment: DESIGN
    variables:
    - group: DESIGN_users
    pool:
      name: '$(pool_name)'
      vmImage: '$(pool_image)'
    strategy:
      runOnce:    #rolling, canary are the other strategies that are supported
        deploy:
          steps:
          - checkout: self
            submodules: "true"
            persistCredentials: "true"
            fetchDepth: 0
          - download: none
          - bash: printenv | grep RESOURCES_PIPELINE_ | sort
            displayName: Print pipeline resource variables
          - template: /pipelines/api-update-steps-template.yml
            parameters:
              api_id: ${{parameters.api_id}}
              update_url: ${{parameters.update_url}}

# - template: /pipelines/api-inject-stages-template.yml
#   parameters:
#     template: /pipelines/api-export-api-stages-template.yml
#     parameters:
#       api_project: ${{parameters.api_project}}
#       commitMessage: Update ${{parameters.api_project}} API triggered by run $(resources.pipeline.trigger-pipeline.runName) of pipeline $(resources.pipeline.trigger-pipeline.pipelineName)