trigger: none

# resources:
#   pipelines:
#   - pipeline: trigger-pipeline # Name of the pipeline resource.
#     source: 'Execute JMeter Load Test' # The name of the pipeline referenced by this pipeline resource.
#     trigger: true

variables:
- group: Log_purging_approval
- group: Project_configuration

stages:
- template: /pipelines/api-inject-stages-template.yml
  parameters:
    template: /pipelines/api-purge-data-stages-template.yml
    parameters: []