# Pipeline for apig staging

trigger: none

# resources:
#   pipelines:
#   - pipeline: trigger-pipeline # Name of the pipeline resource.
#     source: 'Helm Scale API Gateway clusters' # The name of the pipeline referenced by this pipeline resource.
#     trigger: true

variables:
- group: 'Project Configuration'

stages:
- template: /pipelines/api-validate-haft-stages-template.yml
  parameters:
    stages:
    - name: PROD_INT
      instances:
      - name: PROD_INT_01
        pool: $(pool_name)
        image: $(pool_image)
      - name: PROD_INT_02
        pool: $(pool_name)
        image: $(pool_image)
      haft:
        pool: $(pool_name)
        image: $(pool_image)
    - name: PROD_EXT
      instances:
      - name: PROD_EXT_01
        pool: $(pool_name)
        image: $(pool_image)
      - name: PROD_EXT_02
        pool: $(pool_name)
        image: $(pool_image)
      haft:
        pool: $(pool_name)
        image: $(pool_image)