parameters:
- name: template
  type: object
- name: parameters
  type: object
- name: environment_set
  default: webm_io
- name: build_instance
  default: Default Mapping

stages:
# - template: api-inject-stages-${{parameters.environment_set}}-template.yml
#   parameters: ${{parameters}}
- ${{ if eq('', '' ) }}:
  - template: api-inject-stages-treffer-template.yml
    parameters: ${{parameters}}
- ${{ else }}:
  - template: api-inject-stages-niete-template.yml
    parameters: ${{parameters}}