# Pipeline for apig staging

trigger: none

parameters:
- name: tenant
  displayName: Deploy API project on API Gateway stages in which tenant?
  type: string
  default: playground
  values:
  - playground
  - realworld
- name: apiProject
  displayName: Deploy which API project?
  type: string

variables:
- template: /${{parameters.tenant}}/variables/variables-aliases-template.yml
# - template: /${{parameters.tenant}}/variables/variables-artifactory-template.yml

name: $(Date:yyyyMMdd).$(Rev:r)-${{parameters.apiProject}}

stages:
- template: /pipelines/api-deploy-stages-template.yml
  parameters:
    apiProject: ${{parameters.apiProject}}
    tenant: ${{parameters.tenant}}
    build_stage:
      name: BUILD
      instances:
      - name: BUILD_01
        pool: vmsspoolagents
        image: ubuntu-latest
        targets:
        - DEV_INT
      - name: BUILD_02
        pool: vmsspoolagents
        image: ubuntu-latest
        targets:
        - DEV_EXT
      - name: BUILD_03
        pool: vmsspoolagents
        image: ubuntu-latest
        targets:
        - STAGE_INT
      - name: BUILD_04
        pool: vmsspoolagents
        image: ubuntu-latest
        targets:
        - STAGE_EXT
      - name: BUILD_05
        pool: vmsspoolagents
        image: ubuntu-latest
        targets:
        - PROD_INT
      - name: BUILD_06
        pool: vmsspoolagents
        image: ubuntu-latest
        targets:
        - PROD_EXT
    target_stages:
    - name: DEV_INT
      instances:
      - name: DEV_INT
        pool: vmsspoolagents
        image: ubuntu-latest
    - name: DEV_EXT
      instances:
      - name: DEV_EXT
        pool: vmsspoolagents
        image: ubuntu-latest
    - name: STAGE_INT
      instances:
      - name: STAGE_INT
        pool: vmsspoolagents
        image: ubuntu-latest
    - name: STAGE_EXT
      instances:
      - name: STAGE_EXT
        pool: vmsspoolagents
        image: ubuntu-latest
    - name: PROD_INT
      instances:
      - name: PROD_INT_01
        pool: vmsspoolagents
        image: ubuntu-latest
      - name: PROD_INT_02
        pool: vmsspoolagents
        image: ubuntu-latest
    - name: PROD_EXT
      instances:
      - name: PROD_EXT_01
        pool: vmsspoolagents
        image: ubuntu-latest
      - name: PROD_EXT_02
        pool: vmsspoolagents
        image: ubuntu-latest
