trigger: none

# resources:
#   pipelines:
#   - pipeline: trigger-pipeline # Name of the pipeline resource.
#     source: 'Configure API Gateways' # The name of the pipeline referenced by this pipeline resource.
#     trigger: true

parameters:
- name: api_project
  displayName: Deploy which API project?
  type: string
- name: environment_set
  displayName: Deploy APIs on API Gateways in which environment set?
  default: Default
  values:
  - Default
  - webm_io
  - azure_demo_01
- name: selected_target
  displayName: Deploy on which target(s)?
  default: 'All (execpt DESIGN)'
  values:
  - 'All (execpt DESIGN)'
  - DEV_INT
  - DEV_EXT
  - TEST_INT
  - TEST_EXT
  - PROD_INT
  - PROD_EXT
  - DESIGN
  - 'All (including DESIGN)'
- name: build_instance
  displayName: Build on which BUILD instance?
  default: Default Mapping
  values:
  - Default Mapping
  - BUILD_01
  - BUILD_02
  - BUILD_03
  - BUILD_04
  - BUILD_05
  - BUILD_06
  - BUILD_07

name: "$(Date:yyyyMMdd).$(Rev:r)-${{parameters.api_project}}"

stages:
- template: /pipelines/api-inject-stages-template.yml
  parameters:
    template: /pipelines/api-build-and-deploy-stages-template.yml
    parameters: []
    build_instance: ${{parameters.build_instance}}
    api_project: ${{parameters.api_project}}
    eligible_targets:
    - api_projects:
      - ${{parameters.api_project}}
      targets:
      - DEV_INT
      - DEV_EXT
      - TEST_INT
      - TEST_EXT
      - PROD_INT
      - PROD_EXT
      - DESIGN
    selected_target: ${{parameters.selected_target}}
    ${{ if ne(parameters.environment_set, 'Default')}}:
      environment_set: ${{ parameters.environment_set }}