# Pipeline for apig staging

trigger: none

parameters:
- name: tenant
  displayName: Export API Gateway configuration in which tenant?
  type: string
  default: playground
  values:
  - playground
  - realworld
- name: sourceType
  displayName: Export API Gateway configuration from which API Gateway?
  type: string
  values:
  - CONFIG
  - BUILD
  - DEV_INT
  - DEV_EXT
  - STAGE_INT
  - STAGE_EXT
  - PROD_INT
  - PROD_EXT
- name: commitMessage
  displayName: Message for the commit in Git?
  type: string

stages:
- template: /pipelines/api-export-config-stages-template.yml  # Template reference
  parameters:
    tenant: ${{parameters.tenant}}
    sourceType: ${{parameters.sourceType}}
    commitMessage: ${{parameters.commitMessage}}
    source_types:
    - stage: CONFIG
      pool: vmsspoolagents
      image: ubuntu-latest
    - stage: BUILD
      pool: vmsspoolagents
      image: ubuntu-latest
    - stage: DEV_INT
      pool: vmsspoolagents
      image: ubuntu-latest
    - stage: DEV_EXT
      pool: vmsspoolagents
      image: ubuntu-latest
    - stage: STAGE_INT
      pool: vmsspoolagents
      image: ubuntu-latest
    - stage: STAGE_EXT
      pool: vmsspoolagents
      image: ubuntu-latest
    - stage: PROD_INT
      pool: vmsspoolagents
      image: ubuntu-latest
    - stage: PROD_EXT
      pool: vmsspoolagents
      image: ubuntu-latest