trigger: none

parameters:
- name: api_project
  displayName: Deploy which API project?
  type: string
  values:
  # - number_conversion
  - ping
  - odata_tutorial
  # - star_wars
  - petstore
  - petstore_basicauth
  - petstore_versioning
  - postman_echo
  # - postman_echo_jwt
  # - postman_echo_oauth2
  - postman_mocking
  - multiple_tenants
  - security_alias
  - 'other (Please specify below)'
- name: api_project_other
  displayName: Deploy which other API project?
  type: string
  default: 'n/a'
- name: build_instance
  displayName: Build on which BUILD instance?
  default: Default Mapping
  values:
  - Default Mapping
  - BUILD_01
  - BUILD_02
  - BUILD_03
  - BUILD_04
  - BUILD_05
  - BUILD_06
  - BUILD_07

variables:
- group: Project_configuration
- ${{ if ne(parameters.api_project, 'other (Please specify below)') }}:
  - name: api_project
    value: ${{parameters.api_project}}
- ${{ else }}:
  - name: api_project
    value: ${{parameters.api_project_other}}

name: $(Date:yyyyMMdd).$(Rev:r)-$(api_project)

stages:
- template: /pipelines/api-inject-stages-template.yml
  parameters:
    template: /pipelines/api-build-and-deploy-stages-template.yml
    parameters:
      deployment_sets:
      - api_projects:
        - ${{ if ne(parameters.api_project, 'other (Please specify below)') }}:
          - ${{parameters.api_project}}
        - ${{ else }}:
          - ${{parameters.api_project_other}}
        targets:
        - DESIGN
    build_instance: ${{parameters.build_instance}}