# Pipeline for apig staging

trigger:
  branches:
    include:
    - azure-demo

resources:
  pipelines:
  - pipeline: trigger-pipeline # Name of the pipeline resource.
    source: 'Helm Deploy API Gateway' # The name of the pipeline referenced by this pipeline resource.
    trigger: true # Run this pipeline when any run of test-remote-invoke completes

stages:
- template: /pipelines/api-configure-stages-template.yml  # Template reference
  parameters:
    tenant: playground
    target_types:
    - DEV_EXT