parameters:
- name: template
  type: object
- name: parameters
  type: object
- name: api_project
  default: All
- name: environment_set
  default: webm_io
- name: selected_target
  default: 'All (including DESIGN)'
- name: selected_stage
  default: 'All'
- name: build_instance
  default: Default Mapping
- name: eligible_targets
  displayName: Which sets of API projects can be deployed on which API Gateway stages?
  type: object
  default:
  - api_projects:
    # - number_conversion
    - ping
    - odata_tutorial
    # - star_wars
    targets:
    - DEV_INT
    - DEV_EXT
    - TEST_INT
    - TEST_EXT
    - PROD_INT
    - PROD_EXT
  - api_projects:
    - petstore
    # - petstore_basicauth
    - petstore_versioning
    targets:
    - DEV_INT
    - TEST_INT
    - PROD_INT
  - api_projects:
    - postman_echo
    # - postman_echo_jwt
    # - postman_echo_oauth2
    - postman_mocking
    # - multiple_tenants
    - security_alias
    targets:
    - DEV_EXT
    - TEST_EXT
    - PROD_EXT
  - api_projects:
    # - number_conversion
    - odata_tutorial
    - ping
    # - star_wars
    - petstore
    - petstore_basicauth
    - petstore_versioning
    - postman_echo
    # - postman_echo_jwt
    # - postman_echo_oauth2
    - postman_mocking
    - multiple_tenants
    - security_alias
    targets:
    - DESIGN

stages:
- template: api-inject-stages-template-${{parameters.environment_set}}.yml
  parameters: ${{parameters}}