# Pipeline for apig staging

trigger: none

parameters:
- name: tenant
  displayName: Export API project from API Gateway CONFIG in which tenant?
  type: string
  default: playground
  values:
  - playground
  - realworld
- name: apiProject
  displayName: Export which API project?
  type: string
- name: commitMessage
  displayName: Message for the commit in Git?
  type: string

name: $(Date:yyyyMMdd).$(Rev:r)-${{parameters.apiProject}}

stages:
- stage: CONFIG
  jobs:
  - job: Export_API_from_API_Gateway_CONFIG
    variables:
    - template: /${{parameters.tenant}}/variables/CONFIG/variables-template.yml
    pool:
      name: 'vmssagentpool'
      vmImage: 'ubuntu-latest'
    steps:
    - checkout: self
      submodules: "true"
      persistCredentials: "true"
      clean: "true"
    - template: /pipelines/api-export-api-template.yml  # Template reference
      parameters:
        apiProject: ${{parameters.apiProject}}
        source_environment: $(environment)
        source_type: CONFIG
        tenant: ${{parameters.tenant}}
    - template: /pipelines/commit-template.yml  # Template reference
      parameters:
        commitMessage: ${{parameters.commitMessage}}