# Pipeline for apig staging

trigger: none

parameters:
- name: tenant
  displayName: Configure API Gateway in which tenant?
  type: string
  default: playground
  values:
  - playground
  - realworld

stages:
- template: /pipelines/api-configure-stages-template.yml  # Template reference
  parameters:
    tenant: ${{parameters.tenant}}
    target_types:
    - CONFIG
    - BUILD
    - DEV_INT
    - DEV_EXT
    - STAGE_INT
    - STAGE_EXT
    - PROD_INT
    - PROD_EXT