parameters:
- name: template
  type: string
- name: parameters
  type: object
- name: api_project
  default: All
- name: environment_set
  default: webm_io
- name: selected_target
  default: 'All (including DESIGN)'
- name: selected_stage
  default: 'All'
- name: build_instance
  type: string
  default: Default Mapping

stages:
- template: api-inject-stages-template-${{parameters.environment_set}}.yml
  parameters: ${{parameters}}