# Pipeline for apig staging

trigger: none

resources:
  pipelines:
  - pipeline: trigger-pipeline # Name of the pipeline resource.
    source: 'Deploy Mock API' # The name of the pipeline referenced by this pipeline resource.
    trigger: true # Run this pipeline when any run of test-remote-invoke completes

pool:
  vmImage: ubuntu-latest

steps:
- task: AzureLoadTest@1
  inputs:
    azureSubscription: 'sub-ps-wminno-container-sbx'
    loadTestConfigFile: 'loadtesting/loadtest.yaml'
    resourceGroup: 'azure-demo-load-testing'
    loadTestResource: 'azure-demo-load-testing'

- publish: $(System.DefaultWorkingDirectory)/loadTest
  artifact: results