parameters:
- name: tenant
  displayName: Purge analytics data on API Gateway stages in which tenant?
  type: string
  default: playground
  values:
  - playground
  - realworld
- name: target_stages
  displayName: Purge analytics data on which API Gateway stages?
  type: object
  default:
  - name: CONFIG
    jobs:
    - name: CONFIG
      pool: vmsspoolagents
      image: ubuntu-latest
  - name: BUILD
    jobs:
    - name: BUILD
      pool: vmsspoolagents
      image: ubuntu-latest
  - name: DEV_INT
    jobs:
    - name: DEV_INT
      pool: vmsspoolagents
      image: ubuntu-latest
  - name: DEV_EXT
    jobs:
    - name: DEV_EXT
      pool: vmsspoolagents
      image: ubuntu-latest
  - name: STAGE_INT
    jobs:
    - name: STAGE_INT
      pool: vmsspoolagents
      image: ubuntu-latest
  - name: STAGE_EXT
    jobs:
    - name: STAGE_EXT
      pool: vmsspoolagents
      image: ubuntu-latest
  - name: PROD_INT
    jobs:
    - name: PROD_INT_01
      pool: vmsspoolagents
      image: ubuntu-latest
    - name: PROD_INT_02
      pool: vmsspoolagents
      image: ubuntu-latest
  - name: PROD_EXT
    jobs:
    - name: PROD_EXT_01
      pool: vmsspoolagents
      image: ubuntu-latest
    - name: PROD_EXT_02
      pool: vmsspoolagents
      image: ubuntu-latest

stages:
- ${{ each target_stage in parameters.target_stages }}:
  - stage: ${{ target_stage.name }}
    dependsOn: []
    jobs:
    - ${{ each job in target_stage.jobs }}:
      - deployment: Purge_Data_on_${{ job.name }}
        environment: ${{ job.name }}
        variables:
        - group: $(tenant)_${{ job.name }}_users
        pool:
          name: '${{ job.pool }}'
          vmImage: '${{ job.image }}'
        strategy:
          runOnce:    #rolling, canary are the other strategies that are supported
            deploy:
              steps:
              - checkout: self
                submodules: "true"
                persistCredentials: "true"
              - template: /pipelines/api-purge-data-steps-template.yml
                parameters:
                  environment: ${{ job.name }}_environment.json
                  type: ${{ target_stage.name }}
                  tenant: ${{parameters.tenant}}
              - bash: echo "##vso[build.addbuildtag]${{job.name}}"
                displayName: Add build tag