parameters:
- name: template
  type: string
- name: parameters
  type: object
- name: stages
  type: object
  default:
  - name: DESIGN
    is_design_stage: true
    instances:
    - DESIGN
  - name: BUILD
    is_build_stage: true
    instances:
    - BUILD
  - name: DEV_INT
    instances:
    - DEV_INT
  - name: DEV_EXT
    instances:
    - DEV_EXT
  - name: TEST_INT
    instances:
    - TEST_INT
  - name: TEST_EXT
    instances:
    - TEST_EXT
  - name: PROD_INT
    configure_haft: true
    instances:
    - PROD_INT
  - name: PROD_EXT
    configure_haft: true
    instances:
    - PROD_EXT
- name: build_instances_mapping
  type: object
  default:
    DESIGN: BUILD
    DEV_INT: BUILD
    DEV_EXT: BUILD
    TEST_INT: BUILD
    TEST_EXT: BUILD
    PROD_INT: BUILD
    PROD_EXT: BUILD
- name: build_instance
  type: string
  default: Default Mapping

stages:
- template: ${{parameters.template}}
  parameters:
    ${{ each stage in parameters.stages }}:
      ${{ if stage.is_design_stage }}:
        design_stage: ${{stage}}
      ${{ if stage.is_build_stage }}:
        build_stage: ${{stage}}
    target_stages:
    - ${{ each stage in parameters.stages }}:
      - ${{ if not(stage.is_build_stage) }}:
        - ${{stage}}
    all_stages: ${{parameters.stages}}
    build_instances_mapping: ${{parameters.build_instances_mapping}}
    ${{ each parameter in parameters.parameters}}:
      ${{parameter.key}}: ${{parameter.value}}