parameters:
- name: template
  type: object
- name: parameters
  type: object
- name: build_instance
  default: Default Mapping

stages:
- template: api-inject-stages-webm_io-template.yml
  parameters: ${{parameters}}