parameters:
  type: ''

steps:
- script: |
    newman run postman/collections/utilities/haft/Configure_HAFT_${{parameters.type}}.json --reporters cli \
    --env-var haft_manager_01_user='$(haft_manager_01_user)' \
    --env-var haft_manager_01_password='$(haft_manager_01_password)' \
    --env-var haft_manager_02_user='$(haft_manager_02_user)' \
    --env-var haft_manager_02_password='$(haft_manager_02_password)' \
    -e environments/$(project_name)/${{parameters.type}}_haft_environment.json
  workingDirectory: '$(System.DefaultWorkingDirectory)'
  displayName: 'Initialize High Availability and Fault Tolerance for API Gateway ${{parameters.type}}'

- bash: sleep 60
  displayName: Wait 60 seconds for HAFT ring to form

- script: |
    newman run postman/collections/utilities/haft/Validate_HAFT_${{parameters.type}}.json --reporters cli \
    --env-var haft_manager_01_user='$(haft_manager_01_user)' \
    --env-var haft_manager_01_password='$(haft_manager_01_password)' \
    --env-var haft_manager_02_user='$(haft_manager_02_user)' \
    --env-var haft_manager_02_password='$(haft_manager_02_password)' \
    -e environments/$(project_name)/${{parameters.type}}_haft_environment.json
  workingDirectory: '$(System.DefaultWorkingDirectory)'
  displayName: 'Validate High Availability and Fault Tolerance for API Gateway ${{parameters.type}}'