parameters:
- name: tenant
  displayName: Export API Gateway configuration in which tenant?
  type: string
  default: playground
  values:
  - playground
  - realworld
- name: sourceType
  displayName: Export API Gateway configuration from which API Gateway?
  type: string
  values:
  - CONFIG
  - BUILD
  - DEV_INT
  - DEV_EXT
  - STAGE_INT
  - STAGE_EXT
  - PROD_INT
  - PROD_EXT
- name: commitMessage
  displayName: Message for the commit in Git?
  type: string
- name: source_types
  displayName: List of stages
  type: object
  default:
  - stage: CONFIG
    pool: Azure Pipelines
    image: ubuntu-latest
  - stage: BUILD
    pool: Azure Pipelines
    image: ubuntu-latest
  - stage: DEV_INT
    pool: Azure Pipelines
    image: ubuntu-latest
  - stage: DEV_EXT
    pool: Azure Pipelines
    image: ubuntu-latest
  - stage: STAGE_INT
    pool: Azure Pipelines
    image: ubuntu-latest
  - stage: STAGE_EXT
    pool: Azure Pipelines
    image: ubuntu-latest
  - stage: PROD_INT
    pool: Azure Pipelines
    image: ubuntu-latest
  - stage: PROD_EXT
    pool: Azure Pipelines
    image: ubuntu-latest

stages:
- ${{ each type in parameters.source_types }}:
  - ${{ if eq(type.stage, parameters.sourceType) }}:
    - stage: ${{ type.stage }}
      jobs:
      - deployment: Export_config_from_API_Gateway_${{ type.stage }}
        environment: ${{ type.stage }}
        variables:
        - template: /${{parameters.tenant}}/variables/${{ type.stage }}/variables-template.yml
        pool:
          name: '${{ type.pool }}'
          vmImage: '${{ type.image }}'
        strategy:
          runOnce:    #rolling, canary are the other strategies that are supported
            deploy:
              steps:
              - checkout: self
                submodules: "true"
                persistCredentials: "true"
              - template: /pipelines/api-export-config-template.yml  # Template reference
                parameters:
                  environment: $(environment)
                  type: ${{ type.stage }}
                  tenant: ${{parameters.tenant}}
              - template: /pipelines/commit-template.yml  # Template reference
                parameters:
                  commitMessage: ${{parameters.commitMessage}}
              - bash: echo "##vso[build.addbuildtag]${{type.stage}}"
                displayName: Add build tag