trigger: none

resources:
  pipelines:
  - pipeline: trigger # Name of the pipeline resource.
    source: trigger-pipeline # The name of the pipeline referenced by this pipeline resource.
    project: trigger-project # Required only if the source pipeline is in another project
    trigger: true

parameters:
- name: api_project
  displayName: Import and export which API project?
  type: string
  default: petstore
- name: build_instance
  displayName: Build on which BUILD instance?
  type: string
  default: BUILD_01
  values:
  - BUILD_01
  - BUILD_02
  - BUILD_03
  - BUILD_04
  - BUILD_05
  - BUILD_06
  - BUILD_07
- name: api_id
  displayName: Update which API?
  type: string
  default: f3d2a3c1-0f83-43ab-a6ec-215b93e2ecf5
- name: update_url
  displayName: Update using which URL?
  type: string
  default: https://petstore.swagger.io/v2/swagger.json

variables:
- group: Project_configuration
- name: api_project
  value: ${{parameters.api_project}}

name: $(Date:yyyyMMdd).$(Rev:r)-$(api_project)

stages:
- template: /pipelines/api-inject-stages-template.yml
  parameters:
    template: /pipelines/api-build-and-deploy-stages-template.yml
    parameters:
      deployment_sets:
      - api_projects:
        - ${{parameters.api_project}}
        targets:
        - DESIGN
    build_instance: ${{parameters.build_instance}}

- stage: DESIGN_Update
  jobs:
  - deployment: Update_API_on_API_Gateway_DESIGN
    environment: DESIGN
    variables:
    - group: DESIGN_users
    pool:
      name: '$(pool_name)'
      vmImage: '$(pool_image)'
    strategy:
      runOnce:    #rolling, canary are the other strategies that are supported
        deploy:
          steps:
          - checkout: self
            submodules: "true"
            persistCredentials: "true"
            fetchDepth: 0
          - download: none
          - bash: printenv | grep RESOURCES_PIPELINE_ | sort
            displayName: Print pipeline resource variables
          - template: /pipelines/api-update-steps-template.yml
            parameters:
              api_id: ${{parameters.api_id}}
              update_url: ${{parameters.update_url}}

- template: /pipelines/api-inject-stages-template.yml
  parameters:
    template: /pipelines/api-export-api-stages-template.yml
    parameters:
      api_project: ${{parameters.api_project}}
      commitMessage: Update ${{parameters.api_project}} API triggered by run $(resources.pipeline.trigger-pipeline.runName) of pipeline $(resources.pipeline.trigger-pipeline.pipelineName)