trigger: none

parameters:
- name: api_project
  displayName: Deploy which API project(s)?
  type: string
  values:
  - All
  - number_conversion
  - ping
  - odata_tutorial
  - star_wars
  - petstore
  - petstore_basicauth
  - petstore_versioning
  - postman_echo
  - postman_echo_jwt
  - postman_echo_oauth2
  - postman_mocking
  - multiple_tenants
  - security_alias
- name: environment_set
  displayName: Deploy APIs on API Gateways in which environment set?
  default: Default
  values:
  - Default
  - webm_io
  - azure_demo_01
- name: selected_target
  displayName: Deploy on which target(s)?
  default: 'All (execpt DESIGN)'
  values:
  - 'All (execpt DESIGN)'
  - DEV_INT
  - DEV_EXT
  - TEST_INT
  - TEST_EXT
  - PROD_INT
  - PROD_EXT
  - DESIGN
  - 'All (including DESIGN)'
- name: build_instance
  displayName: Build on which BUILD instance?
  default: Default Mapping
  values:
  - Default Mapping
  - BUILD_01
  - BUILD_02
  - BUILD_03
  - BUILD_04
  - BUILD_05
  - BUILD_06
  - BUILD_07

variables:
- group: Project_configuration

name: "$(Date:yyyyMMdd).$(Rev:r)-${{parameters.api_project}}"

stages:
- template: /pipelines/api-inject-stages-template.yml
  parameters:
    template: /pipelines/api-build-and-deploy-stages-template.yml
    parameters: []
    build_instance: ${{parameters.build_instance}}
    api_project: ${{parameters.api_project}}
    selected_target: ${{parameters.selected_target}}
    ${{ if ne(parameters.environment_set, 'Default')}}:
      environment_set: ${{ parameters.environment_set }}
    ignore_eligible_targets: "false"