trigger: none
  # branches:
  #   include:
  #   - azure-demo

# resources:
#   pipelines:
#   - pipeline: trigger-pipeline # Name of the pipeline resource.
#     source: 'Helm Deploy API Gateways' # The name of the pipeline referenced by this pipeline resource.
#     trigger: true

parameters:
- name: environment_set
  displayName: Configure API Gateway(s) in which environment set?
  default: webm_io
  values:
  - webm_io
  - azure_demo_01
- name: selected_stage
  displayName: Configure which API Gateway stage(s)?
  default: 'All'
  values:
  - 'All'
  - DESIGN
  - BUILD
  - DEV_INT
  - DEV_EXT
  - TEST_INT
  - TEST_EXT
  - PROD_INT
  - PROD_EXT

stages:
- template: /pipelines/api-inject-stages-template.yml
  parameters:
    template: /pipelines/api-configure-stages-template.yml
    parameters: []
    ${{ if ne(parameters.environment_set, 'Default')}}:
      environment_set: ${{ parameters.environment_set }}
    selected_stage: ${{ parameters.selected_stage }}