# Pipeline for apig staging

trigger: none

variables:
  ${{ if startsWith(variables['Build.DefinitionName'], 'wm_test_apigw_staging') }}:
    tenant: playground
  ${{ if startsWith(variables['Build.DefinitionName'], 'wm_apigw_staging') }}:
    tenant: realworld
  targetTypes: "CONFIG,BUILD,DEV_INT,DEV_EXT,STAGE_INT,STAGE_EXT,PROD_INT,PROD_EXT"

stages:
- ${{ each targetType in split(variables.targetTypes, ',')}}:
  - stage: ${{ targetType }}
    variables:
      targetType: ${{ targetType }}
    jobs:
    - job: Configure_API_Gateway_${{ targetType }}
      variables:
      - template: /${{variables.tenant}}/variables/${{variables.targetType}}/variables-template.yml
      pool:
        name: '$(agent_pool)'
        vmImage: '$(agent_pool_vmImage)'
      steps:
      - checkout: self
        submodules: "true"
        persistCredentials: "true"
      - template: /pipelines/api-configure-template.yml  # Template reference
        parameters:
          environment: $(environment)
          type: $(targetType)
          tenant: $(tenant)