# Pipeline for apig staging

trigger: none

# To do: Add commit-message and source_type as pipeline parameters (vs. pipeline variable)
# parameters:
# - name: commit-message
#   type: string
# - name: source_type
#   type: string
#   default: 'CONFIG'

variables:
  ${{ if startsWith(variables['Build.DefinitionName'], 'wm_test_apigw_staging') }}:
    tenant: playground
  ${{ if startsWith(variables['Build.DefinitionName'], 'wm_apigw_staging') }}:
    tenant: realworld
  sourceTypes: "CONFIG,BUILD,DEV_INT,DEV_EXT,STAGE_INT,STAGE_EXT,PROD_INT,PROD_EXT"

stages:
- ${{ each sourceType in split(variables.sourceTypes, ',')}}:
  - stage: ${{ sourceType }}
    variables:
      sourceType: ${{ sourceType }}
    jobs:
    - job: Export_config_from_API_Gateway_${{ sourceType }}
      variables:
      - template: /${{variables.tenant}}/variables/${{variables.sourceType}}/variables-template.yml
      pool:
        name: '$(agent_pool)'
        vmImage: '$(agent_pool_vmImage)'
      steps:
      - checkout: self
        submodules: "true"
        persistCredentials: "true"
        clean: "true"
      - template: /pipelines/api-export-config-template.yml  # Template reference
        parameters:
          environment: $(environment)
          type: $(sourceType)
          tenant: $(tenant)
      - template: /pipelines/commit-template.yml  # Template reference