# Pipeline for apig staging

trigger: none

parameters:
- name: tenant
  displayName: Export API Gateway configuration in which tenant?
  type: string
  default: playground
  values:
  - playground
  - realworld
- name: sourceType
  displayName: Export API Gateway configuration from which API Gateway?
  type: string
  values:
  - stage: CONFIG
    pool: vmssagentpool
    image: ubuntu-latest
  - stage: BUILD
    pool: vmssagentpool
    image: ubuntu-latest
  - stage: DEV_INT
    pool: vmssagentpool
    image: ubuntu-latest
  - stage: DEV_EXT
    pool: vmssagentpool
    image: ubuntu-latest
  - stage: STAGE_INT
    pool: vmssagentpool
    image: ubuntu-latest
  - stage: STAGE_EXT
    pool: vmssagentpool
    image: ubuntu-latest
  - stage: PROD_INT
    pool: vmssagentpool
    image: ubuntu-latest
  - stage: PROD_EXT
    pool: vmssagentpool
    image: ubuntu-latest
- name: commitMessage
  displayName: Message for the commit in Git?
  type: string

stages:
- stage: ${{parameters.sourceType.stage}}
  jobs:
  - deployment: Export_config_from_API_Gateway_${{parameters.sourceType.stage}}
    environment: '${{parameters.sourceType.stage}}'
    variables:
    - template: /${{parameters.tenant}}/variables/${{parameters.sourceType.stage}}/variables-template.yml
    strategy:
      runOnce:    #rolling, canary are the other strategies that are supported
        deploy:
          pool:
            name: '${{parameters.sourceType.pool}}'
            vmImage: '${{parameters.sourceType.image}}'
          steps:
          - checkout: self
            submodules: "true"
            persistCredentials: "true"
            clean: "true"
          - template: /pipelines/api-export-config-template.yml  # Template reference
            parameters:
              environment: $(environment)
              type: ${{parameters.sourceType.stage}}
              tenant: ${{parameters.tenant}}
          - template: /pipelines/commit-template.yml  # Template reference
            parameters:
              commitMessage: ${{parameters.commitMessage}}