parameters:
- name: build_stage
  type: object
- name: target_stage
  type: object
- name: api_project
  type: string
- name: deployment_target
  type: string
- name: build_instances_mapping
  type: object
- name: environment_set

jobs:
- deployment: 'Build_${{parameters.api_project}}_for_${{parameters.deployment_target}}'
  environment: '${{parameters.build_stage.name}}_instances'
  variables:
  - group: ${{parameters.build_stage.name}}_users
  - ${{ if not(parameters.target_stage.is_design_stage) }}:
    - group: ${{parameters.deployment_target}}_value_substitutions
  pool:
    name: '$(build_pool_name)'
    vmImage: '$(build_pool_image)'
  strategy:
    runOnce:    #rolling, canary are the other strategies that are supported
      deploy:
        steps:
        - checkout: self
          submodules: "true"
          persistCredentials: "true"
          fetchDepth: 0
        - download: none
        - bash: |
            agentName=$(echo $AGENT_NAME)
            echo "Agent Name: $agentName"
            echo "##vso[task.setvariable variable=agent_name]$agentName"  # Set an output variable
          displayName: Retrieve agent name
        - template: /pipelines/api-build-steps-template.yml
          parameters:
            environment_set: ${{parameters.environment_set}}
            api_project: ${{parameters.api_project}}
            build_environment: "API_Gateway_$(agent_name)_environment.json"
            build_stage_name: ${{parameters.build_stage.name}}
            build_instance_name: $(agent_name)
            target_type: ${{parameters.deployment_target}}
            prepare_condition: ${{true}}
            test_condition: ${{ not(parameters.target_stage.is_design_stage) }}
            replace_condition: ${{ not(parameters.target_stage.is_design_stage) }}
        - template: /pipelines/api-store-build-template.yml
          parameters:
            target_type: ${{parameters.deployment_target}}
            api_project: ${{parameters.api_project}}
        - bash: |
            echo "##vso[build.addbuildtag]${{parameters.environment_set}}"
            echo "##vso[build.addbuildtag]${{parameters.build_stage.name}}"
            echo "##vso[build.addbuildtag]${{parameters.api_project}}"
            echo "##vso[build.addbuildtag]$(agent_name)"
            echo "##vso[build.addbuildtag]${{parameters.api_project}}_$(agent_name)"
          displayName: Add build tags
        # - template: /pipelines/api-store-build-artifactory-template.yml
        #   parameters:
        #     target_type: $(targetType)