parameters:
  type
  instance

steps:
- bash: |
    echo "##vso[task.setvariable variable=environment_insecureflag]`jq -r '.values[] | select(.key == "insecureflag") | .value' environments/${{parameters.environment_set}}/${{parameters.environment}}`"
  workingDirectory: '$(System.DefaultWorkingDirectory)'
  displayName: 'Read and parse API Gateway ${{parameters.instance}} configuration, extract insecureflag'

- script: |
    newman run postman/collections/utilities/haft/Configure_HAFT_listener_on_${{parameters.instance}}.json --reporters cli \
    --env-var haft_manager_user='$(haft_manager_user)' \
    --env-var haft_manager_password='$(haft_manager_password)' \
    -e environments/${{parameters.environment_set}}/${{parameters.environment}} \
    -g environments/${{parameters.environment_set}}/API_Gateway_${{parameters.type}}_haft_globals.json \
    --export-globals environments/${{parameters.environment_set}}/API_Gateway_${{parameters.type}}_haft_globals.json \
    $(environment_insecureflag)
    echo "##vso[task.setvariable variable=node_name;isOutput=true]`jq -r '.values[] | select(.key == "nodeName") | .value' environments/${{parameters.environment_set}}/API_Gateway_${{parameters.type}}_haft_globals.json`"
  workingDirectory: '$(System.DefaultWorkingDirectory)'
  displayName: 'Initialize High Availability and Fault Tolerance (HAFT) listener for API Gateway ${{parameters.instance}}'
  name: setoutputvar