# Pipeline for apig staging

trigger:
  branches:
    include:
    - azure-demo

resources:
  pipelines:
  - pipeline: trigger-pipeline # Name of the pipeline resource.
    source: 'Helm Deploy API Gateways' # The name of the pipeline referenced by this pipeline resource.
    trigger: true # Run this pipeline when any run of test-remote-invoke completes

parameters:
- name: tenant
  displayName: Configure API Gateway in which tenant?
  type: string
  default: playground
  values:
  - playground
  - realworld

variables:
- group: 'Project Configuration'

stages:
- template: /pipelines/api-configure-stages-template.yml  # Template reference
  parameters:
    tenant: ${{parameters.tenant}}
    target_types:
    - stage: CONFIG
      pool: vmsspoolagents
      image: ubuntu-latest
    - stage: BUILD
      pool: vmsspoolagents
      image: ubuntu-latest
    - stage: DEV_INT
      pool: vmsspoolagents
      image: ubuntu-latest
    - stage: DEV_EXT
      pool: vmsspoolagents
      image: ubuntu-latest
    - stage: STAGE_INT
      pool: vmsspoolagents
      image: ubuntu-latest
    - stage: STAGE_EXT
      pool: vmsspoolagents
      image: ubuntu-latest
    - stage: PROD_INT
      pool: vmsspoolagents
      image: ubuntu-latest
    - stage: PROD_EXT
      pool: vmsspoolagents
      image: ubuntu-latest