trigger: none
  # branches:
  #   include:
  #   - azure-demo

# resources:
#   pipelines:
#   - pipeline: trigger-pipeline # Name of the pipeline resource.
#     source: 'Helm Deploy API Gateways' # The name of the pipeline referenced by this pipeline resource.
#     trigger: true

variables:
- group: Project_configuration
- name: foo
  value: bar

stages:
# - template: /pipelines/api-inject-stages-template.yml
#   parameters:
#     template: /pipelines/api-configure-stages-template.yml
#     parameters: []
- ${{ if eq(variables.foo, 'bar') }}:
  - template: api-inject-stages-treffer-template.yml
    parameters: ${{parameters}}
- ${{ else }}:
  - template: api-inject-stages-niete-template.yml
    parameters: ${{parameters}}