parameters:
- name: template
  type: string
- name: parameters
  type: object
- name: stages
  type: object
  default:
  - name: DESIGN
    is_design_stage: true
    instances:
    - DESIGN
  - name: BUILD
    is_build_stage: true
    instances:
    - BUILD
  - name: DEV_INT
    instances:
    - DEV_INT
  - name: DEV_EXT
    instances:
    - DEV_EXT
  - name: TEST_INT
    instances:
    - TEST_INT
  - name: TEST_EXT
    instances:
    - TEST_EXT
  - name: PROD_INT
    instances:
    - PROD_INT
  - name: PROD_EXT
    instances:
    - PROD_EXT
- name: build_instances_mapping
  type: object
  default:
    DESIGN: BUILD
    DEV_INT: BUILD
    DEV_EXT: BUILD
    TEST_INT: BUILD
    TEST_EXT: BUILD
    PROD_INT: BUILD
    PROD_EXT: BUILD
- name: environment_set
- name: selected_targets
- name: build_instance
  type: string
  default: Default Mapping
- name: eligible_targets
  displayName: Which sets of API projects can be deployed on which API Gateway stages?
  type: object
  default:
  - api_projects:
    # - number_conversion
    - ping
    - odata_tutorial
    # - star_wars
    targets:
    - DEV_INT
    - DEV_EXT
    - TEST_INT
    - TEST_EXT
    - PROD_INT
    - PROD_EXT
  - api_projects:
    - petstore
    # - petstore_basicauth
    - petstore_versioning
    targets:
    - DEV_INT
    - TEST_INT
    - PROD_INT
  - api_projects:
    - postman_echo
    # - postman_echo_jwt
    # - postman_echo_oauth2
    - postman_mocking
    # - multiple_tenants
    - security_alias
    targets:
    - DEV_EXT
    - TEST_EXT
    - PROD_EXT
  - api_projects:
    # - number_conversion
    - odata_tutorial
    - ping
    # - star_wars
    - petstore
    - petstore_basicauth
    - petstore_versioning
    - postman_echo
    # - postman_echo_jwt
    # - postman_echo_oauth2
    - postman_mocking
    - multiple_tenants
    - security_alias
    targets:
    - DESIGN

stages:
- template: ${{parameters.template}}
  parameters:
    ${{ each stage in parameters.stages }}:
      ${{ if stage.is_design_stage }}:
        design_stage: ${{stage}}
      ${{ if stage.is_build_stage }}:
        build_stage: ${{stage}}
        ${{ if containsValue(stage.instances, parameters.build_instance) }}:
          build_instances_mapping:
            DESIGN: ${{parameters.build_instance}}
            DEV_INT: ${{parameters.build_instance}}
            DEV_EXT: ${{parameters.build_instance}}
            TEST_INT: ${{parameters.build_instance}}
            TEST_EXT: ${{parameters.build_instance}}
            PROD_INT: ${{parameters.build_instance}}
            PROD_EXT: ${{parameters.build_instance}}
        ${{ else }}:
          build_instances_mapping: ${{parameters.build_instances_mapping}}
    target_stages:
    - ${{ each stage in parameters.stages }}:
      - ${{ if not(stage.is_build_stage) }}:
        - ${{stage}}
    all_stages: ${{parameters.stages}}
    # ${{ if eq(parameters.build_instance, 'Default Mapping')}}:
    #   build_instances_mapping: ${{parameters.build_instances_mapping}}
    # ${{ else }}:
    #   build_instances_mapping:
    #     DESIGN: ${{parameters.build_instance}}
    #     DEV_INT: ${{parameters.build_instance}}
    #     DEV_EXT: ${{parameters.build_instance}}
    #     TEST_INT: ${{parameters.build_instance}}
    #     TEST_EXT: ${{parameters.build_instance}}
    #     PROD_INT: ${{parameters.build_instance}}
    #     PROD_EXT: ${{parameters.build_instance}}
    environment_set: ${{parameters.environment_set}}
    deployment_sets:
    - ${{ each eligible_target in parameters.eligible_targets }}:
      - api_projects: ${{ eligible_target.api_projects }}
        targets: # ${{ eligible_target.targets }}
        - ${{ each target in eligible_target.targets }}:
          - ${{ if eq(parameters.selected_targets, target) }}:
            - ${{target}}
          - ${{ elseif eq(parameters.selected_targets, 'All') }}:
            - ${{target}}
          - ${{ elseif and(eq(parameters.selected_targets, 'All (execpt DESIGN)'), ne(target, 'DESIGN')) }}:
            - ${{target}}
    ${{ each parameter in parameters.parameters}}:
      ${{parameter.key}}: ${{parameter.value}}