trigger: none

# resources:
#   pipelines:
#   - pipeline: trigger-pipeline # Name of the pipeline resource.
#     source: 'Configure API Gateways' # The name of the pipeline referenced by this pipeline resource.
#     trigger: true

parameters:
- name: environment_set
  displayName: Deploy APIs on API Gateways in which environment set?
  default: Default
  values:
  - Default
  - webm_io
  - azure-demo-01
- name: build_instance
  displayName: Build on which BUILD instance?
  default: Default Mapping
  values:
  - Default Mapping
  - BUILD_01
  - BUILD_02
  - BUILD_03
  - BUILD_04
  - BUILD_05
  - BUILD_06
  - BUILD_07

variables:
- group: Project_configuration

stages:
- template: /pipelines/api-inject-stages-template.yml
  parameters:
    template: /pipelines/api-build-and-deploy-stages-template.yml
    parameters:
      deployment_sets:
      - api_projects:
        # - number_conversion
        - ping
        - odata_tutorial
        # - star_wars
        targets:
        - DEV_INT
        - DEV_EXT
        - TEST_INT
        - TEST_EXT
        - PROD_INT
        - PROD_EXT
      - api_projects:
        - petstore
        # - petstore_basicauth
        - petstore_versioning
        targets:
        - DEV_INT
        - TEST_INT
        - PROD_INT
      - api_projects:
        - postman_echo
        # - postman_echo_jwt
        # - postman_echo_oauth2
        - postman_mocking
        # - multiple_tenants
        - security_alias
        targets:
        - DEV_EXT
        - TEST_EXT
        - PROD_EXT
    build_instance: ${{parameters.build_instance}}
    ${{ if ne(parameters.environment_set, 'Default')}}:
      environment_set: ${{ parameters.environment_set }}