# Pipeline for apig staging

trigger: none
  # branches:
  #   include:
  #   - azure-demo

resources:
  pipelines:
  - pipeline: trigger-pipeline # Name of the pipeline resource.
    source: 'Configure API Gateways' # The name of the pipeline referenced by this pipeline resource.
    trigger:
      tags:
      - DESIGN

parameters:
- name: tenant
  displayName: Deploy API project on API Gateway stages in which tenant?
  type: string
  default: playground
  values:
  - playground
  - realworld

variables:
- template: /${{parameters.tenant}}/variables/variables-aliases-template.yml
# - template: /${{parameters.tenant}}/variables/variables-artifactory-template.yml
- group: 'Project Configuration'

# name: $(Date:yyyyMMdd).$(Rev:r)-${{parameters.apiProject}}

stages:
- template: /pipelines/api-multi-deploy-stages-template.yml
  parameters:
    tenant: ${{parameters.tenant}}
    build_stage:
      name: BUILD
      instances:
      - name: $(design_build_environment)
        pool: $(pool_name)
        image: $(pool_image)
        targets:
        - DESIGN
    target_stages:
    - name: DESIGN
      instances:
      - name: DESIGN
        pool: $(pool_name)
        image: $(pool_image)
    deployment_sets:
    - apiProjects:
      # - number_conversion
      - odata_tutorial
      - ping
      # - star_wars
      - petstore
      - petstore_basicauth
      - petstore_versioning
      - postman_echo
      # - postman_echo_jwt
      # - postman_echo_oauth2
      - postman_mocking
      - multiple_tenants
      - security_alias
      targets:
      - DESIGN