# Pipeline for apig staging

trigger:
  branches:
    include:
    - azure-demo

resources:
  pipelines:
  - pipeline: trigger-pipeline # Name of the pipeline resource.
    # source: 'Helm Deploy API Gateways' # The name of the pipeline referenced by this pipeline resource.
    source: 'Terraform Create Front Door endpoints' # The name of the pipeline referenced by this pipeline resource.
    trigger: true # Run this pipeline when any run of test-remote-invoke completes

parameters:
- name: tenant
  displayName: Configure API Gateway in which tenant?
  type: string
  default: playground
  values:
  - playground
  - realworld

variables:
- group: 'Project Configuration'

stages:
- template: /pipelines/api-configure-stages-template.yml
  parameters:
    tenant: ${{parameters.tenant}}
    stages:
    - name: CONFIG
      instances:
      - name: CONFIG
        pool: vmsspoolagents
        image: ubuntu-latest
    - name: BUILD
      instances:
      - name: BUILD_01
        pool: vmsspoolagents
        image: ubuntu-latest
      - name: BUILD_02
        pool: vmsspoolagents
        image: ubuntu-latest
      - name: BUILD_03
        pool: vmsspoolagents
        image: ubuntu-latest
      - name: BUILD_04
        pool: vmsspoolagents
        image: ubuntu-latest
      - name: BUILD_05
        pool: vmsspoolagents
        image: ubuntu-latest
      - name: BUILD_06
        pool: vmsspoolagents
        image: ubuntu-latest
      - name: BUILD_07
        pool: vmsspoolagents
        image: ubuntu-latest
    - name: DEV_INT
      instances:
      - name: DEV_INT
        pool: vmsspoolagents
        image: ubuntu-latest
    - name: DEV_EXT
      instances:
      - name: DEV_EXT
        pool: vmsspoolagents
        image: ubuntu-latest
    - name: STAGE_INT
      instances:
      - name: STAGE_INT
        pool: vmsspoolagents
        image: ubuntu-latest
    - name: STAGE_EXT
      instances:
      - name: STAGE_EXT
        pool: vmsspoolagents
        image: ubuntu-latest
    - name: PROD_INT
      instances:
      - name: PROD_INT_01
        pool: vmsspoolagents
        image: ubuntu-latest
      - name: PROD_INT_02
        pool: vmsspoolagents
        image: ubuntu-latest
      haft:
        pool: vmsspoolagents
        image: ubuntu-latest
    - name: PROD_EXT
      instances:
      - name: PROD_EXT_01
        pool: vmsspoolagents
        image: ubuntu-latest
      - name: PROD_EXT_02
        pool: vmsspoolagents
        image: ubuntu-latest
      haft:
        pool: vmsspoolagents
        image: ubuntu-latest