# Pipeline for apig staging

trigger: none

parameters:
- name: tenant
  displayName: Export API project from API Gateway CONFIG in which tenant?
  type: string
  default: playground
  values:
  - playground
  - realworld
- name: apiProject
  displayName: Export which API project?
  type: string
- name: commit-message
  displayName: Message for the commit in Git?
  type: string

variables:
- template: /${{parameters.tenant}}/variables/CONFIG/variables-template.yml

name: $(Date:yyyyMMdd).$(Rev:r)-${{parameters.apiProject}}

pool:
  name: '$(agent_pool)'
  vmImage: '$(agent_pool_vmImage)'

steps:
- checkout: self
  submodules: "true"
  persistCredentials: "true"
  clean: "true"

- template: /pipelines/api-export-api-template.yml  # Template reference
  parameters:
    apiProject: ${{parameters.apiProject}}
    source_environment: $(environment)
    source_type: CONFIG
    tenant: ${{parameters.tenant}}

- template: /pipelines/commit-template.yml  # Template reference
  parameters:
    commit-message: ${{parameters.commit-message}}