parameters:
- name: template
  type: object
- name: parameters
  type: object
- name: build_instance
  default: Default Mapping
- name: environment_set
  default: webm_io

stages:
- template: api-inject-stages-${{parameters.environment_set}}-template.yml
  parameters: ${{parameters}}