parameters:
- name: template
  type: object
- name: parameters
  type: object
- name: api_project
  default: All
- name: environment_set
  default: webm_io
- name: selected_target
  default: 'All (including DESIGN)'
- name: build_instance
  default: Default Mapping
- name: eligible_targets
  type: object

stages:
- template: api-inject-stages-${{parameters.environment_set}}-template.yml
  parameters: ${{parameters}}