# Pipeline for apig staging

trigger: none

resources:
  pipelines:
  - pipeline: trigger-pipeline # Name of the pipeline resource.
    source: 'Execute JMeter Load Test' # The name of the pipeline referenced by this pipeline resource.
    trigger: true # Run this pipeline when any run of test-remote-invoke completes

variables:
- group: 'Shutdown approval'

parameters:
- name: tenant
  displayName: Purge analytics data on API Gateway stages in which tenant?
  type: string
  default: playground
  values:
  - playground
  - realworld

stages:
- template: /pipelines/api-purge-data-stages-template.yml  # Template reference
  parameters:
    tenant: ${{parameters.tenant}}
    target_types:
    - stage: CONFIG
      pool: vmsspoolagents
      image: ubuntu-latest
    - stage: BUILD
      pool: vmsspoolagents
      image: ubuntu-latest
    - stage: DEV_INT
      pool: vmsspoolagents
      image: ubuntu-latest
    - stage: DEV_EXT
      pool: vmsspoolagents
      image: ubuntu-latest
    - stage: STAGE_INT
      pool: vmsspoolagents
      image: ubuntu-latest
    - stage: STAGE_EXT
      pool: vmsspoolagents
      image: ubuntu-latest
    - stage: PROD_INT
      pool: vmsspoolagents
      image: ubuntu-latest
    - stage: PROD_EXT
      pool: vmsspoolagents
      image: ubuntu-latest