parameters:
- name: template
  type: object
- name: parameters
  type: object
- name: environment_set
  default: webm_io
- name: selected_targets
  default: All
- name: build_instance
  default: Default Mapping

stages:
- template: api-inject-stages-${{parameters.environment_set}}-template.yml
  parameters: ${{parameters}}