parameters:
- name: tenant
  displayName: Purge analytics data on API Gateway stages in which tenant?
  type: string
  default: playground
  values:
  - playground
  - realworld
- name: target_stages
  displayName: Purge analytics data on which API Gateway stages?
  type: object

stages:
- ${{ each target_stage in parameters.target_stages }}:
  - stage: ${{ target_stage.name }}
    dependsOn: []
    jobs:
    - ${{ each job in target_stage.jobs }}:
      - deployment: Purge_Data_on_${{ job.name }}
        environment: ${{ job.name }}
        variables:
        - group: ${{parameters.tenant}}_${{ job.name }}_users
        pool:
          name: '${{ job.pool }}'
          vmImage: '${{ job.image }}'
        strategy:
          runOnce:    #rolling, canary are the other strategies that are supported
            deploy:
              steps:
              - checkout: self
                submodules: "true"
                persistCredentials: "true"
              - template: /pipelines/api-purge-data-steps-template.yml
                parameters:
                  environment: ${{ job.name }}_environment.json
                  type: ${{ target_stage.name }}
                  tenant: ${{parameters.tenant}}
              - bash: echo "##vso[build.addbuildtag]${{job.name}}"
                displayName: Add build tag