parameters:
- name: template
  type: string
- name: parameters
  type: object
- name: stages
  type: object
  default:
  - name: DESIGN
    build_instance: BUILD_01
    is_design_stage: true
    instances:
    - DESIGN
  - name: BUILD
    is_build_stage: true
    instances:
    - BUILD_01
    - BUILD_02
    - BUILD_03
    - BUILD_04
    - BUILD_05
    - BUILD_06
    - BUILD_07
  - name: DEV_INT
    build_instance: BUILD_02
    instances:
    - DEV_INT
  - name: DEV_EXT
    build_instance: BUILD_03
    instances:
    - DEV_EXT
  - name: TEST_INT
    build_instance: BUILD_04
    instances:
    - TEST_INT
  - name: TEST_EXT
    build_instance: BUILD_05
    instances:
    - TEST_EXT
  - name: PROD_INT
    build_instance: BUILD_06
    configure_haft: true
    instances:
    - PROD_INT_01
    - PROD_INT_02
  - name: PROD_EXT
    build_instance: BUILD_07
    configure_haft: true
    instances:
    - PROD_EXT_01
    - PROD_EXT_02

stages:
- template: ${{ parameters.template }}
  parameters:
    ${{ each stage in parameters.stages }}:
      ${{ if stage.is_design_stage }}:
        design_stage: ${{ stage }}
      ${{ if stage.is_build_stage }}:
        build_stage: ${{ stage }}
    target_stages:
    - ${{ each stage in parameters.stages }}:
      - ${{ if ne(stage.is_build_stage) }}:
        - ${{ stage }}
    all_stages: ${{ parameters.stages }}
    ${{ each parameter in parameters.parameters}}:
      ${{ parameter.key }}: ${{ parameter.value }}