trigger: none

parameters:
- name: api_project
  displayName: Export which API project?
  type: string
- name: environment_set
  displayName: Export API from DESIGN API Gateway in which environment set?
  default: Default
  values:
  - Default
  - webm_io
  - azure_demo_01
- name: commitMessage
  displayName: Message for the commit in Git?
  type: string

name: $(Date:yyyyMMdd).$(Rev:r)-${{parameters.api_project}}

stages:
- template: /pipelines/api-inject-stages-template.yml
  parameters:
    template: /pipelines/api-export-api-stages-template.yml
    parameters:
      commitMessage: ${{parameters.commitMessage}}
      api_project: ${{parameters.api_project}}
    ${{ if ne(parameters.environment_set, 'Default')}}:
      environment_set: ${{ parameters.environment_set }}