trigger: none

parameters:
- name: api_project
  displayName: Export which API project?
  type: string
  values:
  - number_conversion
  - odata_tutorial
  - ping
  - star_wars
  - petstore
  - petstore_basicauth
  - petstore_versioning
  - postman_echo
  - postman_echo_jwt
  - postman_echo_oauth2
  - postman_mocking
  - multiple_tenants
  - security_alias
- name: environment_set
  displayName: Export API from DESIGN API Gateway in which environment set?
  default: Default
  values:
  - Default
  - webm_io
  - azure-demo-01
- name: commitMessage
  displayName: Message for the commit in Git?
  type: string

variables:
- group: Project_configuration

name: $(Date:yyyyMMdd).$(Rev:r)-${{parameters.api_project}}

stages:
- template: /pipelines/api-inject-stages-template.yml
  parameters:
    template: /pipelines/api-export-api-stages-template.yml
    parameters:
      commitMessage: ${{parameters.commitMessage}}
      api_project: ${{parameters.api_project}}
    ${{ if ne(parameters.environment_set, 'Default')}}:
      environment_set: ${{ parameters.environment_set }}