parameters:
- name: template
  type: object
- name: parameters
  type: object
- name: build_instance

stages:
- template: api-inject-stages-webm_io-template.yml
  parameters: ${{parameters.parameters}}
  build_instance: ${{parameters.build_instance}}