parameters:
- name: stage_groups
  type: object

stages:
- ${{ each stage_group in parameters.stage_groups }}:
  - ${{ each stage in stage_group.stages }}:
    - stage: ${{ stage.name }}
      dependsOn: []
      jobs:
      - ${{ each instance in stage.instances }}:
        - deployment: Configure_API_Gateway_${{ instance }}
          environment: ${{ instance }}
          variables:
          - group: ${{ stage.name }}_users
          - group: ${{ instance }}_users
          pool:
            name: '$(pool_name)'
            vmImage: '$(pool_image)'
          strategy:
            runOnce:    #rolling, canary are the other strategies that are supported
              deploy:
                steps:
                - checkout: self
                  submodules: "true"
                  persistCredentials: "true"
                - download: none
                - template: /pipelines/api-configure-steps-template.yml
                  parameters:
                    environment: ${{ instance }}_environment.json
                    type: ${{ stage.name }}
                - bash: echo "##vso[build.addbuildtag]${{instance}}"
                  displayName: Add build tag

      # - ${{ if gt(length(stage.instances),1) }}: # Configure HAFT if more than one instance per stage
      - ${{ if startsWith(stage.name, 'PROD') }}: # Configure HAFT on PROD stages
        - deployment: Configure_HAFT_for_API_Gateway_${{ stage.name }}
          environment: ${{ stage.name }}_HAFT
          variables:
          - group: ${{ stage.name }}_HAFT_users
          pool:
            name: '$(pool_name)'
            vmImage: '$(pool_image)'
          strategy:
            runOnce:    #rolling, canary are the other strategies that are supported
              deploy:
                steps:
                - checkout: self
                  submodules: "true"
                  persistCredentials: "true"
                - download: none
                - template: /pipelines/api-configure-haft-steps-template.yml
                  parameters:
                    type: ${{ stage.name }}
                - bash: echo "##vso[build.addbuildtag]${{ stage.name }}_HAFT"
                  displayName: Add build tag