parameters:
- name: tenant
  displayName: Purge analytics data on API Gateway stages in which tenant?
  type: string
  default: playground
  values:
  - playground
  - realworld
- name: target_types
  displayName: Purge analytics data on which API Gateway stages?
  type: object
  default:
  - stage: CONFIG
    pool: vmssagentpool
    image: ubuntu-latest
  - stage: BUILD
    pool: vmssagentpool
    image: ubuntu-latest
  - stage: DEV_INT
    pool: vmssagentpool
    image: ubuntu-latest
  - stage: DEV_EXT
    pool: vmssagentpool
    image: ubuntu-latest
  - stage: STAGE_INT
    pool: vmssagentpool
    image: ubuntu-latest
  - stage: STAGE_EXT
    pool: vmssagentpool
    image: ubuntu-latest
  - stage: PROD_INT
    pool: vmssagentpool
    image: ubuntu-latest
  - stage: PROD_EXT
    pool: vmssagentpool
    image: ubuntu-latest

stages:
- ${{ each targetType in parameters.target_types }}:
  - stage: ${{ targetType.stage }}
    jobs:
    - deployment: Purge_Data_on_${{ targetType.stage }}
      environment: ${{ targetType.stage }}
      variables:
      - template: /${{parameters.tenant}}/variables/${{ targetType.stage }}/variables-template.yml
      pool:
        name: '${{ targetType.pool }}'
        vmImage: '${{ targetType.image }}'
      strategy:
        runOnce:    #rolling, canary are the other strategies that are supported
          deploy:
            steps:
            - checkout: self
              submodules: "true"
              persistCredentials: "true"
            - template: /pipelines/api-purge-data-template.yml  # Template reference
              parameters:
                environment: $(environment)
                type: ${{ targetType.stage }}
                tenant: ${{parameters.tenant}}