parameters:
- name: tenant
  displayName: Configure API Gateway in which tenant?
  type: string
- name: apiProjects
  displayName: Deploy which API projects?
  type: object
- name: stages
  displayName: Configure API Gateway in which stages?
  type: object

stages:
- ${{ each apiProject in parameters.apiProjects }}:
  - ${{ each stage in parameters.stages }}:
    - stage: ${{ stage.name }}_${{ apiProject }}
      dependsOn: []
      jobs:
      - ${{ each job in stage.jobs }}:
        - deployment: Configure_API_Gateway_${{ job.name }}
          environment: ${{ job.name }}
          variables:
          - group: ${{parameters.tenant}}_${{ job.name }}_users
          pool:
            name: '${{ job.pool }}'
            vmImage: '${{ job.image }}'
          strategy:
            runOnce:    #rolling, canary are the other strategies that are supported
              deploy:
                steps:
                - checkout: self
                  submodules: "true"
                  persistCredentials: "true"
                - download: none

      - ${{ each job in stage.buildjobs }}:
        - deployment: Configure_API_Gateway_${{ job.name }}
          environment: ${{ stage.name }}
          variables:
          - group: ${{parameters.tenant}}_${{ job.name }}_users
          pool:
            name: '${{ job.pool }}'
            vmImage: '${{ job.image }}'
            demands: Agent.Name -equals ${{ job.name }}
          strategy:
            runOnce:    #rolling, canary are the other strategies that are supported
              deploy:
                steps:
                - checkout: self
                  submodules: "true"
                  persistCredentials: "true"
                - download: none
