# Pipeline for apig staging

trigger: none

parameters:
- name: apiId
  displayName: Publish which API (ID)?
  type: string

name: $(Date:yyyyMMdd).$(Rev:r)-${{parameters.apiId}}

stages:
- stage: CONFIG
  variables:
    targetType: CONFIG
  jobs:
  - job: Publish_on_CONFIG
    variables:
    - template: /playground/variables/CONFIG/variables-template.yml
    pool:
      name: '$(agent_pool)'
      vmImage: '$(agent_pool_vmImage)'
    steps:
    - checkout: self
      submodules: "true"
      persistCredentials: "true"
    - template: /pipelines/api-publish-template.yml  # Template reference
      parameters:
        apiId: ${{parameters.apiId}}
        target_environment: $(environment)
        target_type: CONFIG
        tenant: playground