parameters:
- name: tenant
  displayName: Deploy API project on API Gateway stages in which tenant?
  type: string
  default: playground
  values:
  - playground
  - realworld
- name: apiProject
  displayName: Deploy which API project?
  type: string
- name: build_type
  displayName: Build on which stage?
  type: object
  default: 
  - stage: BUILD
    pool: vmsspoolagents
    image: ubuntu-latest
- name: target_types
  displayName: Deploy to which stages?
  type: object
  default:
  - stage: DEV_INT
    pool: vmsspoolagents
    image: ubuntu-latest
  - stage: DEV_EXT
    pool: vmsspoolagents
    image: ubuntu-latest
  - stage: STAGE_INT
    pool: vmsspoolagents
    image: ubuntu-latest
  - stage: STAGE_EXT
    pool: vmsspoolagents
    image: ubuntu-latest
  - stage: PROD_INT
    pool: vmsspoolagents
    image: ubuntu-latest
  - stage: PROD_EXT
    pool: vmsspoolagents
    image: ubuntu-latest

stages:
- ${{ each targetType in parameters.target_types }}:
  - stage: ${{ targetType.stage }}
    jobs:
    - deployment: 'Build_${{parameters.apiProject}}_for_${{ targetType.stage }}'
      environment: '${{ parameters.build_type[0].stage }}'
      variables:
      - template: /${{parameters.tenant}}/variables/${{ parameters.build_type[0].stage }}/variables-template.yml
      pool:
        name: '${{ parameters.build_type[0].pool }}'
        vmImage: '${{ parameters.build_type[0].image }}'
      strategy:
        runOnce:    #rolling, canary are the other strategies that are supported
          deploy:
            steps:
            - checkout: self
              submodules: "true"
              persistCredentials: "true"
            - download: none
            - template: /pipelines/api-build-template.yml  # Template reference
              parameters:
                apiProject: ${{parameters.apiProject}}
                build_environment: $(environment)
                target_type: ${{ targetType.stage }}
                prep_condition: ${{true}}
                test_condition: ${{ ne('${{ targetType.stage }}', 'CONFIG') }}
                tenant: ${{parameters.tenant}}
            - template: /pipelines/store-build-template.yml  # Template reference
              parameters:
                target_type: ${{ targetType.stage }}
                apiProject: ${{apiProject}}
            - bash: echo "##vso[build.addbuildtag]${{parameters.apiProject}}"
            - bash: echo "##vso[build.addbuildtag]${{parameters.build_type[0].stage}}"
            - bash: echo "##vso[build.addbuildtag]${{parameters.apiProject}}_${{parameters.build_type[0].stage}}"
            # - template: /pipelines/store-build-artifactory-template.yml  # Template reference
            #   parameters:
            #     target_type: $(targetType)

    - deployment: 'Deploy_${{parameters.apiProject}}_to_API_Gateway_${{ targetType.stage }}'
      environment: ${{ targetType.stage }}
      variables:
      - template: /${{parameters.tenant}}/variables/${{ targetType.stage }}/variables-template.yml
      pool:
        name: '${{ targetType.pool }}'
        vmImage: '${{ targetType.image }}'
      strategy:
        runOnce:    #rolling, canary are the other strategies that are supported
          deploy:
            steps:
            - checkout: self
              submodules: "true"
              persistCredentials: "true"
            - template: /pipelines/retrieve-build-template.yml  # Template reference
              parameters:
                  target_type: ${{ targetType.stage }}
                  apiProject: ${{apiProject}}
            - template: /pipelines/api-deploy-template.yml  # Template reference
              parameters:
                apiProject: ${{parameters.apiProject}}
                target_environment: $(environment)
                target_type: ${{ targetType.stage }}
                prep_condition: ${{true}}
                test_condition: ${{ ne('${{ targetType.stage }}', 'CONFIG') }}
                tenant: ${{parameters.tenant}}
            - bash: echo "##vso[build.addbuildtag]${{parameters.apiProject}}"
            - bash: echo "##vso[build.addbuildtag]${{targetType.stage}}"
            - bash: echo "##vso[build.addbuildtag]${{parameters.apiProject}}_${{targetType.stage}}"
      dependsOn: 'Build_${{parameters.apiProject}}_for_${{ targetType.stage }}'
      condition: succeeded()