parameters:
- name: tenant
  displayName: Configure API Gateway in which tenant?
  type: string
  default: playground
  values:
  - playground
  - realworld
- name: target_types
  displayName: Configure API Gateway in which stages?
  type: object
  default:
  - CONFIG
  - BUILD
  - DEV_INT
  - DEV_EXT
  - STAGE_INT
  - STAGE_EXT
  - PROD_INT
  - PROD_EXT

stages:
- ${{ each targetType in parameters.target_types }}:
  - stage: ${{ targetType }}
    variables:
    - name: targetType
      value: ${{ targetType }}
    - template: /${{parameters.tenant}}/variables/${{variables.targetType}}/variables-template.yml
    pool:
      name: 'pool-${{ targetType }}'
      vmImage: 'ubuntu-latest'
    jobs:
    - deployment: Configure_API_Gateway_${{ targetType }}
      environment: ${{ targetType }}
      strategy:
        runOnce:    #rolling, canary are the other strategies that are supported
          deploy:
            steps:
            - checkout: self
              submodules: "true"
              persistCredentials: "true"
            - template: /pipelines/api-configure-template.yml  # Template reference
              parameters:
                environment: $(environment)
                type: $(targetType)
                tenant: ${{parameters.tenant}}