parameters:
- name: design_stage
  type: object
- name: build_stage
  type: object
- name: target_stages
  type: object
- name: all_stages
  type: object

stages:
- ${{ each stage in parameters.all_stages }}:
  - stage: ${{stage.name}}
    dependsOn: []
    jobs:
    - ${{ each instance in stage.instances }}:
      - deployment: Configure_API_Gateway_${{instance}}
        continueOnError: true
        environment: ${{instance}}
        variables:
        - group: ${{stage.name}}_users
        - group: ${{instance}}_users
        pool:
          name: '$(pool_name)'
          vmImage: '$(pool_image)'
        strategy:
          runOnce:    #rolling, canary are the other strategies that are supported
            deploy:
              steps:
              - checkout: self
                submodules: "true"
                persistCredentials: "true"
                fetchDepth: 0
              - download: none
              - bash: cat $(System.DefaultWorkingDirectory)/environments/$(project_name)/${{instance}}_environment.json
                displayName: Check if environment.json file exists
              - template: /pipelines/api-configure-steps-template.yml
                parameters:
                  environment: ${{instance}}_environment.json
                  type: ${{stage.name}}
              - bash: echo "##vso[build.addbuildtag]${{instance}}"
                displayName: Add build tag

    - ${{ if stage.configure_haft }}: # Configure HAFT on PROD stages
      - deployment: Configure_HAFT_for_API_Gateway_${{stage.name}}
        continueOnError: true
        environment: ${{stage.name}}_HAFT
        variables:
        - group: ${{stage.name}}_HAFT_users
        pool:
          name: '$(pool_name)'
          vmImage: '$(pool_image)'
        strategy:
          runOnce:    #rolling, canary are the other strategies that are supported
            deploy:
              steps:
              - checkout: self
                submodules: "true"
                persistCredentials: "true"
                fetchDepth: 0
              - download: none
              - template: /pipelines/api-configure-haft-steps-template.yml
                parameters:
                  type: ${{stage.name}}
              - bash: echo "##vso[build.addbuildtag]${{stage.name}}_HAFT"
                displayName: Add build tag