# Pipeline for apig staging

trigger: none

resources:
  pipelines:
  - pipeline: trigger-pipeline # Name of the pipeline resource.
    source: 'Deploy Mock API' # The name of the pipeline referenced by this pipeline resource.
    trigger: true # Run this pipeline when any run of test-remote-invoke completes

pool:
  vmImage: ubuntu-latest

steps:
- task: AzureCLI@2
  inputs:
    azureSubscription: 'sub-ps-wminno-container-sbx'
    scriptType: 'bash'
    scriptLocation: 'inlineScript'
    inlineScript: |
      echo "##vso[task.setvariable variable=cluster_name]`az aks list --query "[?tags.environment == 'azuredemo'].name" -o tsv`"
      echo "##vso[task.setvariable variable=cluster_rg_name]`az aks list --query "[?tags.environment == 'azuredemo'].resourceGroup" -o tsv`"
      echo "##vso[task.setvariable variable=node_rg_name]`az aks list --query "[?tags.environment == 'azuredemo'].nodeResourceGroup" -o tsv`"
  displayName: Set cluster name, resource group name, node resource group name

- task: AzureCLI@2
  inputs:
    azureSubscription: 'sub-ps-wminno-container-sbx'
    scriptType: 'bash'
    scriptLocation: 'inlineScript'
    inlineScript: |
      echo "##vso[task.setvariable variable=dns_zone_name]`az network dns zone list --resource-group $(node_rg_name) --query "[0].name" -o tsv`"
      echo "##vso[task.setvariable variable=hostname]apigateway-admin.`az network dns zone list --resource-group $(node_rg_name) --query "[0].name" -o tsv`"
      echo "##vso[task.setvariable variable=apihostname]apigateway.`az network dns zone list --resource-group $(node_rg_name) --query "[0].name" -o tsv`"
  displayName: Set DNS zone name

- task: AzureLoadTest@1
  inputs:
    azureSubscription: 'sub-ps-wminno-container-sbx'
    loadTestConfigFile: 'loadtesting/loadtest.yaml'
    resourceGroup: 'azure-demo-load-testing'
    loadTestResource: 'azure-demo-load-testing'
    env: |
      [
        {
        "name": "url",
        "value": "$(apihostname)"
        }
      ]

- publish: $(System.DefaultWorkingDirectory)/loadTest
  artifact: results