# Pipeline for apig staging

trigger: none

parameters:
- name: tenant
  displayName: Export API Gateway configuration in which tenant?
  type: string
  default: playground
  values:
  - playground
  - realworld
- name: source_instance
  displayName: Export API Gateway configuration from which API Gateway?
  type: string
  values:
  - CONFIG
  - BUILD_01
  - BUILD_02
  - BUILD_03
  - BUILD_04
  - BUILD_05
  - BUILD_06
  - BUILD_07
  - DEV_INT
  - DEV_EXT
  - STAGE_INT
  - STAGE_EXT
  - PROD_INT_01
  - PROD_INT_02
  - PROD_EXT_01
  - PROD_EXT_02
- name: commitMessage
  displayName: Message for the commit in Git?
  type: string

stages:
- template: /pipelines/api-export-config-stages-template.yml
  parameters:
    tenant: ${{parameters.tenant}}
    source_instance: ${{parameters.source_instance}}
    commitMessage: ${{parameters.commitMessage}}
    source_types:
    - stage: CONFIG
      pool: vmsspoolagents
      image: ubuntu-latest
    - stage: BUILD
      pool: vmsspoolagents
      image: ubuntu-latest
    - stage: DEV_INT
      pool: vmsspoolagents
      image: ubuntu-latest
    - stage: DEV_EXT
      pool: vmsspoolagents
      image: ubuntu-latest
    - stage: STAGE_INT
      pool: vmsspoolagents
      image: ubuntu-latest
    - stage: STAGE_EXT
      pool: vmsspoolagents
      image: ubuntu-latest
    - stage: PROD_INT
      pool: vmsspoolagents
      image: ubuntu-latest
    - stage: PROD_EXT
      pool: vmsspoolagents
      image: ubuntu-latest