# Pipeline for apig staging

trigger: none

parameters:
- name: tenant
  displayName: Configure API Gateway in which tenant?
  type: string
  default: playground
  values:
  - playground
  - realworld

stages:
- template: /pipelines/api-configure-stages-template.yml  # Template reference
  parameters:
    tenant: ${{parameters.tenant}}
    target_types:
    - stage: CONFIG
      pool: vmssagentpool
      image: ubuntu-latest
    - stage: BUILD
      pool: vmssagentpool
      image: ubuntu-latest
    - stage: DEV_INT
      pool: vmssagentpool
      image: ubuntu-latest
    - stage: DEV_EXT
      pool: vmssagentpool
      image: ubuntu-latest
    - stage: STAGE_INT
      pool: vmssagentpool
      image: ubuntu-latest
    - stage: STAGE_EXT
      pool: vmssagentpool
      image: ubuntu-latest
    - stage: PROD_INT
      pool: vmssagentpool
      image: ubuntu-latest
    - stage: PROD_EXT
      pool: vmssagentpool
      image: ubuntu-latest