# Pipeline for apig staging

trigger: none
  # branches:
  #   include:
  #   - azure-demo

resources:
  pipelines:
  - pipeline: trigger-pipeline # Name of the pipeline resource.
    source: 'Configure API Gateways' # The name of the pipeline referenced by this pipeline resource.
    # source: 'Terraform Create Front Door endpoints' # The name of the pipeline referenced by this pipeline resource.
    trigger: true

parameters:
- name: tenant
  displayName: Deploy API project on API Gateway stages in which tenant?
  type: string
  default: playground
  values:
  - playground
  - realworld

variables:
- template: /${{parameters.tenant}}/variables/variables-aliases-template.yml
# - template: /${{parameters.tenant}}/variables/variables-artifactory-template.yml

# name: $(Date:yyyyMMdd).$(Rev:r)-${{parameters.apiProject}}

stages:
- template: /pipelines/api-multi-deploy-stages-template.yml
  parameters:
    tenant: ${{parameters.tenant}}
    build_stage:
      name: BUILD
      instances:
      - name: BUILD_01
        pool: vmsspoolagents
        image: ubuntu-latest
        targets:
        - DEV_INT
      - name: BUILD_02
        pool: vmsspoolagents
        image: ubuntu-latest
        targets:
        - DEV_EXT
      - name: BUILD_03
        pool: vmsspoolagents
        image: ubuntu-latest
        targets:
        - STAGE_INT
      - name: BUILD_04
        pool: vmsspoolagents
        image: ubuntu-latest
        targets:
        - STAGE_EXT
      - name: BUILD_05
        pool: vmsspoolagents
        image: ubuntu-latest
        targets:
        - PROD_INT
      - name: BUILD_06
        pool: vmsspoolagents
        image: ubuntu-latest
        targets:
        - PROD_EXT
    target_stages:
    - name: DEV_INT
      instances:
      - name: DEV_INT
        pool: vmsspoolagents
        image: ubuntu-latest
    - name: DEV_EXT
      instances:
      - name: DEV_EXT
        pool: vmsspoolagents
        image: ubuntu-latest
    - name: STAGE_INT
      instances:
      - name: STAGE_INT
        pool: vmsspoolagents
        image: ubuntu-latest
    - name: STAGE_EXT
      instances:
      - name: STAGE_EXT
        pool: vmsspoolagents
        image: ubuntu-latest
    - name: PROD_INT
      instances:
      - name: PROD_INT_01
        pool: vmsspoolagents
        image: ubuntu-latest
      - name: PROD_INT_02
        pool: vmsspoolagents
        image: ubuntu-latest
    - name: PROD_EXT
      instances:
      - name: PROD_EXT_01
        pool: vmsspoolagents
        image: ubuntu-latest
      - name: PROD_EXT_02
        pool: vmsspoolagents
        image: ubuntu-latest
    deployment_sets:
    - apiProjects:
      # - number_conversion
      - odata_tutorial
      - ping
      # - star_wars
      targets:
      - DEV_INT
      - DEV_EXT
      - STAGE_INT
      - STAGE_EXT
      - PROD_INT
      - PROD_EXT

    - apiProjects:
      - petstore
      # - petstore_basicauth
      - petstore_versioning
      targets:
      - DEV_INT
      - STAGE_INT
      - PROD_INT

    - apiProjects:
      - postman_echo
      # - postman_echo_jwt
      # - postman_echo_oauth2
      - postman_mocking
      # - multiple_tenants
      # - security_alias
      targets:
      - DEV_EXT
      - STAGE_EXT
      - PROD_EXT