# Pipeline template for apig configuring

parameters:
  environment: ''
  type: ''
  tenant: ''

steps:
- bash: echo Job runs in pool 'vmssagentpool' on VM image 'ubuntu-latest' for tenant '${{parameters.tenant}}' and type '${{parameters.type}}'
  displayName: Job runs in pool 'vmssagentpool' on VM image 'ubuntu-latest' for tenant '${{parameters.tenant}}' and type '${{parameters.type}}'

- bash: |
    if [ -z "$ENVIRONMENT" ]; then
      echo "##vso[task.logissue type=error;]Missing template parameter \"environment\""
      echo "##vso[task.complete result=Failed;]"
    fi
    if [ -z "$TYPE" ]; then
      echo "##vso[task.logissue type=error;]Missing template parameter \"type\""
      echo "##vso[task.complete result=Failed;]"
    fi
    if [ -z "$TENANT" ]; then
      echo "##vso[task.logissue type=error;]Missing template parameter \"tenant\""
      echo "##vso[task.complete result=Failed;]"
    fi
  env:
    ENVIRONMENT: ${{parameters.environment}}
    TYPE: ${{parameters.type}}
    TENANT: ${{parameters.tenant}}
  displayName: Check for required parameters

- task: ArchiveFiles@2
  inputs:
    rootFolderOrFile: '$(System.DefaultWorkingDirectory)/${{parameters.tenant}}/configuration/${{parameters.type}}/assets'
    includeRootFolder: false
    archiveType: 'zip'
    archiveFile: '$(System.DefaultWorkingDirectory)/$(Build.BuildId)_configuration.zip'
    replaceExistingArchive: true
    verbose: true
  displayName: 'Create the API Deployable from the flat representation for ${{parameters.type}} configuration'

- task: PublishBuildArtifacts@1
  inputs:
    pathToPublish: '$(System.DefaultWorkingDirectory)/$(Build.BuildId)_configuration.zip'
    artifactName: '${{parameters.type}}_configuration'

# - bash: |
#    echo "##vso[task.setvariable variable=environment_hostname]`jq -r '.values[] | select(.key == "hostname") | .value' ${{parameters.tenant}}/environments/${{parameters.environment}}`"
#    echo "##vso[task.setvariable variable=environment_ip]`jq -r '.values[] | select(.key == "ip") | .value' ${{parameters.tenant}}/environments/${{parameters.environment}}`"
#    echo "##vso[task.setvariable variable=environment_port]`jq -r '.values[] | select(.key == "port") | .value' ${{parameters.tenant}}/environments/${{parameters.environment}}`"
#    echo "##vso[task.setvariable variable=environment_insecureflag]`jq -r '.values[] | select(.key == "insecureflag") | .value' ${{parameters.tenant}}/environments/${{parameters.environment}}`"
#   workingDirectory: '$(System.DefaultWorkingDirectory)'
#   displayName: 'Read and parse API Gateway ${{parameters.type}} configuration, extract ip, hostname, port and insecureflag'

- bash: |
    echo "##vso[task.setvariable variable=scopes]`jq -c '.' $(System.DefaultWorkingDirectory)/${{parameters.tenant}}/configuration/${{parameters.type}}/scopes.json`"
  workingDirectory: '$(System.DefaultWorkingDirectory)'
  displayName: 'Prepare list of scopes to be imported'

- script: curl -sL https://aka.ms/InstallAzureCLIDeb | sudo bash
  displayName: Install Azure CLI

- task: AzureCLI@2
  inputs:
    azureSubscription: 'sub-ps-wminno-container-sbx'
    scriptType: 'bash'
    scriptLocation: 'inlineScript'
    inlineScript: |
      echo "##vso[task.setvariable variable=cluster_name]`az aks list --query "[?tags.environment == 'azuredemo'].name" -o tsv`"
      echo "##vso[task.setvariable variable=cluster_rg_name]`az aks list --query "[?tags.environment == 'azuredemo'].resourceGroup" -o tsv`"
      echo "##vso[task.setvariable variable=node_rg_name]`az aks list --query "[?tags.environment == 'azuredemo'].nodeResourceGroup" -o tsv`"
  displayName: Set cluster name, resource group name, node resource group name

- task: AzureCLI@2
  inputs:
    azureSubscription: 'sub-ps-wminno-container-sbx'
    scriptType: 'bash'
    scriptLocation: 'inlineScript'
    inlineScript: |
      echo "##vso[task.setvariable variable=dns_zone_name]`az network dns zone list --resource-group $(node_rg_name) --query "[0].name" -o tsv`"
      echo "##vso[task.setvariable variable=hostname]apigateway-admin.`az network dns zone list --resource-group $(node_rg_name) --query "[0].name" -o tsv`"
      echo "##vso[task.setvariable variable=apihostname]apigateway.`az network dns zone list --resource-group $(node_rg_name) --query "[0].name" -o tsv`"
  displayName: Set DNS zone name

- script: |
    newman run utilities/import/ImportConfig.json --reporters cli \
    --env-var importer_user='$(importer_user)' \
    --env-var importer_password='$(importer_password)' \
    --env-var initializer_user='$(initializer_user)' \
    --env-var initializer_password='$(initializer_password)' \
    --env-var scopes='$(scopes)' \
    --env-var file_Loc=$(Build.BuildId)_configuration.zip \
    --env-var hostname='$(hostname)' \
    --env-var ip='$(hostname)' \
    --env-var port='443' \
    --insecure
  workingDirectory: '$(System.DefaultWorkingDirectory)'
  displayName: 'Import the Deployable To API Gateway ${{parameters.type}}'
  # env:
  #   no_proxy: $(environment_ip)

- script: |
    newman run utilities/initialize/Initialize_${{parameters.type}}.json --reporters cli \
    --env-var initializer_user='$(initializer_user)' \
    --env-var initializer_password='$(initializer_password)' \
    --env-var file_Loc=$(Build.BuildId)_configuration.zip \
    --env-var hostname='$(hostname)' \
    --env-var ip='$(hostname)' \
    --env-var port='443' \
    --env-var apihostname='$(apihostname)' \
    --insecure
  workingDirectory: '$(System.DefaultWorkingDirectory)'
  displayName: 'Initialize API Gateway ${{parameters.type}}'
  # env:
  #   no_proxy: $(environment_ip)