trigger: none
  # branches:
  #   include:
  #   - azure-demo

# resources:
#   pipelines:
#   - pipeline: trigger-pipeline # Name of the pipeline resource.
#     source: 'Helm Deploy API Gateways' # The name of the pipeline referenced by this pipeline resource.
#     trigger: true

parameters:
- name: environment_set
  displayName: Configure API Gateway in which environment set?
  default: Default
  values:
  - Default
  - webm_io
  - azure-demo-01

variables:
- group: Project_configuration

stages:
- template: /pipelines/api-inject-stages-template.yml
  parameters:
    template: /pipelines/api-configure-stages-template.yml
    parameters: []
    # ${{ if ne(parameters.environment_set, 'Default')}}:
    #   environment_set: ${{ parameters.environment_set }}
    # ${{ else }}:
    #   environment_set: ${{ variables['Build.Reason'] }}
    ${{ if ne(variables['Build.Reason'], '') }}:
      environment_set: treffer
    ${{ else }}:
      environment_set: niete
