# Pipeline for apig staging

trigger: none

resources:
  pipelines:
  - pipeline: trigger-pipeline # Name of the pipeline resource.
    source: 'Execute JMeter Load Test' # The name of the pipeline referenced by this pipeline resource.
    trigger: true # Run this pipeline when any run of test-remote-invoke completes

variables:
- group: 'Shutdown approval'

parameters:
- name: tenant
  displayName: Purge analytics data on API Gateway stages in which tenant?
  type: string
  default: playground
  values:
  - playground
  - realworld

stages:
- template: /pipelines/api-purge-data-stages-template.yml
  parameters:
    tenant: ${{parameters.tenant}}
    target_stages:
    - name: DESIGN
      jobs:
      - name: DESIGN
        pool: $(pool_name)
        image: $(pool_image)
    - name: BUILD
      jobs:
      - name: BUILD_01
        pool: $(pool_name)
        image: $(pool_image)
      - name: BUILD_02
        pool: $(pool_name)
        image: $(pool_image)
      - name: BUILD_03
        pool: $(pool_name)
        image: $(pool_image)
      - name: BUILD_04
        pool: $(pool_name)
        image: $(pool_image)
      - name: BUILD_05
        pool: $(pool_name)
        image: $(pool_image)
      - name: BUILD_06
        pool: $(pool_name)
        image: $(pool_image)
      - name: BUILD_07
        pool: $(pool_name)
        image: $(pool_image)
    - name: DEV_INT
      jobs:
      - name: DEV_INT
        pool: $(pool_name)
        image: $(pool_image)
    - name: DEV_EXT
      jobs:
      - name: DEV_EXT
        pool: $(pool_name)
        image: $(pool_image)
    - name: TEST_INT
      jobs:
      - name: TEST_INT
        pool: $(pool_name)
        image: $(pool_image)
    - name: TEST_EXT
      jobs:
      - name: TEST_EXT
        pool: $(pool_name)
        image: $(pool_image)
    - name: PROD_INT
      jobs:
      - name: PROD_INT_01
        pool: $(pool_name)
        image: $(pool_image)
      - name: PROD_INT_02
        pool: $(pool_name)
        image: $(pool_image)
    - name: PROD_EXT
      jobs:
      - name: PROD_EXT_01
        pool: $(pool_name)
        image: $(pool_image)
      - name: PROD_EXT_02
        pool: $(pool_name)
        image: $(pool_image)