parameters:
- name: tenant
  displayName: Configure API Gateway in which tenant?
  type: string
  default: playground
  values:
  - playground
  - realworld
- name: stages
  displayName: Configure API Gateway in which stages?
  type: object
  default:
  - name: CONFIG
    jobs:
    - name: CONFIG
      pool: vmsspoolagents
      image: ubuntu-latest
  - name: BUILD
    jobs:
    - name: BUILD
      pool: vmsspoolagents
      image: ubuntu-latest
  - name: DEV_INT
    jobs:
    - name: DEV_INT
      pool: vmsspoolagents
      image: ubuntu-latest
  - name: DEV_EXT
    jobs:
    - name: DEV_EXT
      pool: vmsspoolagents
      image: ubuntu-latest
  - name: STAGE_INT
    jobs:
    - name: STAGE_INT
      pool: vmsspoolagents
      image: ubuntu-latest
  - name: STAGE_EXT
    jobs:
    - name: STAGE_EXT
      pool: vmsspoolagents
      image: ubuntu-latest
  - name: PROD_INT
    configure_haft: true
    jobs:
    - name: PROD_INT_01
      pool: vmsspoolagents
      image: ubuntu-latest
    - name: PROD_INT_02
      pool: vmsspoolagents
      image: ubuntu-latest
  - name: PROD_EXT
    configure_haft: true
    jobs:
    - name: PROD_EXT_01
      pool: vmsspoolagents
      image: ubuntu-latest
    - name: PROD_EXT_02
      pool: vmsspoolagents
      image: ubuntu-latest

stages:
- ${{ each stage in parameters.stages }}:
  - stage: ${{ stage.name }}
    dependsOn: []
    jobs:
    - ${{ each job in stage.jobs }}:
      - deployment: Configure_API_Gateway_${{ job.name }}
        environment: ${{ job.name }}
        variables:
        - template: /${{parameters.tenant}}/variables/${{ job.name }}/variables-template.yml
        pool:
          name: '${{ job.pool }}'
          vmImage: '${{ job.image }}'
        strategy:
          runOnce:    #rolling, canary are the other strategies that are supported
            deploy:
              steps:
              - checkout: self
                submodules: "true"
                persistCredentials: "true"
              - download: none
              - template: /pipelines/api-configure-steps-template.yml
                parameters:
                  environment: $(environment)
                  type: ${{ stage.name }}
                  tenant: ${{parameters.tenant}}
                  configure_haft: ${{ stage.configure_haft }}
              - bash: echo "##vso[build.addbuildtag]${{job.name}}"
                displayName: Add build tag