# Pipeline for apig staging

trigger: none

parameters:
- name: api_project
  displayName: Export which API project?
  type: string
  values:
  # - number_conversion
  - ping
  - odata_tutorial
  # - star_wars
  - petstore
  # - petstore_basicauth
  - petstore_versioning
  - postman_echo
  # - postman_echo_jwt
  # - postman_echo_oauth2
  - postman_mocking
  # - multiple_tenants
  # - security_alias
  - 'other (Please specify below)'
- name: api_project_other
  displayName: Export which other API project?
  type: string
  default: 'n/a'
- name: commitMessage
  displayName: Message for the commit in Git?
  type: string

name: $(Date:yyyyMMdd).$(Rev:r)-${{parameters.api_project}}

variables:
- group: 'Project Configuration'

stages:
- template: /pipelines/api-inject-stages-template.yml
  parameters:
    template: /pipelines/api-export-api-stages-template.yml
    parameters:
      api_project: ${{parameters.api_project}}
      commitMessage: ${{parameters.commitMessage}}