parameters:
- name: tenant
  displayName: Configure API Gateway in which tenant?
  type: string
  default: playground
  values:
  - playground
  - realworld
- name: stages
  displayName: Configure API Gateway in which stages?
  type: object

stages:
- ${{ each stage in parameters.stages }}:
  - stage: ${{ stage.name }}
    dependsOn: []
    jobs:
    - ${{ each job in stage.jobs }}:
      - deployment: Configure_API_Gateway_${{ job.name }}
        environment: ${{ job.name }}
        variables:
        - group: ${{parameters.tenant}}_${{ job.name }}_users
        pool:
          name: '${{ job.pool }}'
          vmImage: '${{ job.image }}'
        strategy:
          runOnce:    #rolling, canary are the other strategies that are supported
            deploy:
              steps:
              - checkout: self
                submodules: "true"
                persistCredentials: "true"
              - download: none
              - template: /pipelines/api-configure-steps-template.yml
                parameters:
                  environment: "${{ job.name }}_environment.json"
                  type: ${{ stage.name }}
                  tenant: ${{parameters.tenant}}
              - bash: echo "##vso[build.addbuildtag]${{job.name}}"
                displayName: Add build tag

    - ${{ each job in stage.configure_haft_jobs }}:
      - deployment: Configure_HAFT_for_API_Gateway_${{ stage.name }}
        environment: ${{ job.name }}
        pool:
          name: '${{ job.pool }}'
          vmImage: '${{ job.image }}'
        strategy:
          runOnce:    #rolling, canary are the other strategies that are supported
            deploy:
              steps:
              - checkout: self
                submodules: "true"
                persistCredentials: "true"
              - download: none
              - template: /pipelines/api-configure-haft-steps-template.yml
                parameters:
                  type: ${{ stage.name }}
                  tenant: ${{parameters.tenant}}
              - bash: echo "##vso[build.addbuildtag]${{job.name}}"
                displayName: Add build tag