# Pipeline for apig staging

trigger: none

parameters:
- name: tenant
  displayName: Purge analytics data on API Gateway stages in which tenant?
  type: string
  default: playground
  values:
  - playground
  - realworld

stages:
- template: /pipelines/api-purge-data-from-stages-template.yml  # Template reference
  parameters:
    tenant: ${{parameters.tenant}}
    target_types:
    - stage: CONFIG
      pool: Azure Pipelines
      image: ubuntu-latest
    - stage: BUILD
      pool: Azure Pipelines
      image: ubuntu-latest
    - stage: DEV_INT
      pool: Azure Pipelines
      image: ubuntu-latest
    - stage: DEV_EXT
      pool: Azure Pipelines
      image: ubuntu-latest
    - stage: STAGE_INT
      pool: Azure Pipelines
      image: ubuntu-latest
    - stage: STAGE_EXT
      pool: Azure Pipelines
      image: ubuntu-latest
    - stage: PROD_INT
      pool: Azure Pipelines
      image: ubuntu-latest
    - stage: PROD_EXT
      pool: Azure Pipelines
      image: ubuntu-latest