trigger: none
  # branches:
  #   include:
  #   - azure-demo

resources:
  pipelines:
  - pipeline: trigger-pipeline # Name of the pipeline resource.
    source: 'Helm Deploy API Gateways' # The name of the pipeline referenced by this pipeline resource.
    trigger: true

variables:
- group: Project_configuration

stages:
- template: /pipelines/api-inject-stages-template.yml
  parameters:
    template: /pipelines/api-configure-stages-template.yml
    parameters: []