parameters:
- name: design_stage
  type: object
- name: build_stage
  type: object
- name: target_stages
  type: object
- name: all_stages
  type: object

stages:
- ${{ each stage in parameters.all_stages }}:
  - stage: ${{stage.name}}
    dependsOn: []
    jobs:
    - ${{ each instance in stage.instances }}:
      - job: Check_environment_file_for_${{instance}}
        pool:
          name: '$(pool_name)'
          vmImage: '$(pool_image)'
        steps:
        - bash: |
            if test -f $(System.DefaultWorkingDirectory)/environments/$(project_name)/${{instance}}_environment.json; then
              echo "##vso[task.setvariable variable=environment_file_exists;isoutput=true]true"
            else
              echo "##vso[task.setvariable variable=environment_file_exists;isoutput=true]false"
              echo "##vso[task.logissue type=warning]Environment file not found: $(System.DefaultWorkingDirectory)/environments/$(project_name)/${{instance}}_environment.json"
              echo "##vso[task.complete result=SucceededWithIssues]Environment file not found: $(System.DefaultWorkingDirectory)/environments/$(project_name)/${{instance}}_environment.json"
            fi
          displayName: Check if environment.json file exists
          name: Check_environment_file
      - deployment: Configure_API_Gateway_${{instance}}
        dependsOn: Check_environment_file_for_${{instance}}
        condition: $[ eq(dependencies.Check_environment_file_for_${{instance}}.outputs['Check_environment_file.environment_file_exists'], "true") ]
        environment: ${{instance}}
        variables:
        - group: ${{stage.name}}_users
        - group: ${{instance}}_users
        pool:
          name: '$(pool_name)'
          vmImage: '$(pool_image)'
        strategy:
          runOnce:    #rolling, canary are the other strategies that are supported
            deploy:
              steps:
              - checkout: self
                submodules: "true"
                persistCredentials: "true"
                fetchDepth: 0
              - download: none
              - template: /pipelines/api-configure-steps-template.yml
                parameters:
                  environment: ${{instance}}_environment.json
                  type: ${{stage.name}}
              - bash: echo "##vso[build.addbuildtag]${{instance}}"
                displayName: Add build tag

    - ${{ if stage.configure_haft }}: # Configure HAFT on PROD stages
      - job: Check_environment_file_haft
        pool:
          name: '$(pool_name)'
          vmImage: '$(pool_image)'
        steps:
        - bash: |
            if test -f $(System.DefaultWorkingDirectory)/environments/$(project_name)/${{stage.name}}_haft_environment.json; then
              echo "##vso[task.setvariable variable=environment_file_exists;isoutput=true]true"
            else
              echo "##vso[task.setvariable variable=environment_file_exists;isoutput=true]false"
              echo "##vso[task.logissue type=warning]Environment file not found: $(System.DefaultWorkingDirectory)/environments/$(project_name)/${{stage.name}}_haft_environment.json.json"
              echo "##vso[task.complete result=SucceededWithIssues]Environment file not found: $(System.DefaultWorkingDirectory)/environments/$(project_name)/${{stage.name}}_haft_environment.json.json"
            fi
          displayName: Check if environment.json file exists
          name: Check_environment_file
      - deployment: Configure_HAFT_for_API_Gateway_${{stage.name}}
        dependsOn: Check_environment_file_haft
        condition: $[ eq(dependencies.Check_environment_file_haft.outputs['Check_environment_file.environment_file_exists'], "true") ]
        environment: ${{stage.name}}_HAFT
        variables:
        - group: ${{stage.name}}_HAFT_users
        pool:
          name: '$(pool_name)'
          vmImage: '$(pool_image)'
        strategy:
          runOnce:    #rolling, canary are the other strategies that are supported
            deploy:
              steps:
              - checkout: self
                submodules: "true"
                persistCredentials: "true"
                fetchDepth: 0
              - download: none
              - template: /pipelines/api-configure-haft-steps-template.yml
                parameters:
                  type: ${{stage.name}}
              - bash: echo "##vso[build.addbuildtag]${{stage.name}}_HAFT"
                displayName: Add build tag