trigger:
- main

prereqs:
- script: |
    #!/bin/bash
    # Fetch parameters.yml and update pipeline YAML files
    ./scripts/update_yaml.sh

pool:
  vmImage: 'ubuntu-latest'

steps:
- script: echo "This is the actual pipeline execution"
  displayName: 'Pipeline Execution'
