trigger: none

# resources:
#   pipelines:
#   - pipeline: trigger-pipeline # Name of the pipeline resource.
#     source: 'Configure API Gateways' # The name of the pipeline referenced by this pipeline resource.
#     trigger: true

parameters:
- name: selected_api_project
  displayName: Deploy which API project?
  type: string
- name: selected_environment_set
  displayName: Deploy API(s) on API Gateway(s) in which environment set?
  default: webm_io
  values:
  - webm_io
  - azure_demo_01
- name: selected_target
  displayName: Deploy on which target(s)?
  default: 'All (execpt DESIGN)'
  values:
  - 'All (execpt DESIGN)'
  - DEV_INT
  - DEV_EXT
  - TEST_INT
  - TEST_EXT
  - PROD_INT
  - PROD_EXT
  - DESIGN
  - 'All (including DESIGN)'
- name: selected_build_environment
  displayName: Build on which BUILD environment?
  default: Default Mapping
  values:
  - Default Mapping
  - BUILD_01
  - BUILD_02
  - BUILD_03
  - BUILD_04
  - BUILD_05
  - BUILD_06
  - BUILD_07

variables:
- group: Project_configuration

name: "$(Date:yyyyMMdd).$(Rev:r)-${{parameters.selected_api_project}}"

stages:
- template: /pipelines/stage-templates/inject-parameters-for-${{parameters.selected_environment_set}}.yml
  parameters:
    template: /pipelines/stage-templates/build-and-deploy-api.yml
    parameters: []
    selected_api_project: ${{parameters.selected_api_project}}
    selected_environment_set: ${{parameters.selected_environment_set}}
    selected_target: ${{parameters.selected_target}}
    selected_build_environment: ${{parameters.selected_build_environment}}
    ignore_eligible_targets: "true"