stages:
- stage: Stage1
  jobs:
  - job: Job1
    steps:
    - script: echo "This is Stage 1, Job 1"

- stage: Stage2
  jobs:
  - job: Job2
    steps:
    - script: echo "This is Stage 2, Job 1"
  
- stage: Stage3
  jobs:
  - job: Job3
    steps:
    - script: echo "This is Stage 3, Job 1"

- job: CountStages
  steps:
  - script: |
      # Count the number of stages by using the length of the stages array
      stage_count=${#STAGES[*]}

      # Print the stage count
      echo "Number of stages in this pipeline: $stage_count"
    displayName: 'Count Stages'