trigger: none
  # branches:
  #   include:
  #   - azure-demo

# resources:
#   pipelines:
#   - pipeline: trigger-pipeline # Name of the pipeline resource.
#     source: 'Helm Deploy API Gateways' # The name of the pipeline referenced by this pipeline resource.
#     trigger: true

parameters:
- name: selected_environment_set
  displayName: Configure API Gateway(s) in which environment set?
  default: webm_io
  values:
  - webm_io
  - azure_demo_01
- name: selected_stage
  displayName: Configure which API Gateway stage(s)?
  default: 'All'
  values:
  - 'All'
  - DESIGN
  - BUILD
  - DEV_INT
  - DEV_EXT
  - TEST_INT
  - TEST_EXT
  - PROD_INT
  - PROD_EXT

stages:
- template: /pipelines/stage-templates/inject-parameters-for-${{parameters.selected_environment_set}}.yml
  parameters:
    template: /pipelines/stage-templates/configure-api-gateway.yml
    parameters: []
    selected_environment_set: ${{parameters.selected_environment_set}}
    selected_stage: ${{parameters.selected_stage}}