trigger: none

parameters:
- name: api_project
  displayName: Export which API project?
  type: string
  values:
  - petstore
  - petstore_basicauth
  - petstore_versioning
  - postman_echo
  - postman_echo_mocking
  - postman_echo_multiple_tenants
  - postman_echo_oauth2
  - postman_echo_jwt
  - postman_echo_security_alias
  - ping
  - number_conversion
  - odata_tutorial
  - countries
- name: environment_set
  displayName: Export API(s) from DESIGN API Gateway in which environment set?
  default: webm_io
  values:
  - webm_io
  - azure_demo_01
- name: commitMessage
  displayName: Message for the commit in Git?
  type: string

name: "$(Date:yyyyMMdd).$(Rev:r)-${{parameters.api_project}}"

stages:
- template: /pipelines/stage-templates/inject-parameters-for-${{parameters.environment_set}}.yml
  parameters:
    template: /pipelines/stage-templates/export-api.yml
    parameters:
      commitMessage: ${{parameters.commitMessage}}
      api_project: ${{parameters.api_project}}
    environment_set: ${{parameters.environment_set}}