trigger: none

parameters:
- name: api_project
  displayName: Export which API project?
  type: string
- name: environment_set
  displayName: Export API(s) from DESIGN API Gateway in which environment set?
  default: webm_io
  values:
  - webm_io
  - azure_demo_01
- name: commitMessage
  displayName: Message for the commit in Git?
  type: string

name: "$(Date:yyyyMMdd).$(Rev:r)-${{parameters.api_project}}"

stages:
- template: /pipelines/stage-templates/inject-${{parameters.environment_set}}.yml
  parameters:
    template: /pipelines/stage-templates/export-api.yml
    parameters:
      commitMessage: ${{parameters.commitMessage}}
      api_project: ${{parameters.api_project}}
    ${{ if ne(parameters.environment_set, 'Default')}}:
      environment_set: ${{ parameters.environment_set }}