trigger: none

parameters:
- name: selected_api_project
  displayName: Export which API project?
  type: string
- name: selected_environment_set
  displayName: Export API(s) from DESIGN API Gateway in which environment set?
  default: webm_io
  values:
  - webm_io
  - azure_demo_01
- name: commit_message
  displayName: Message for the commit in Git?
  type: string

name: "$(Date:yyyyMMdd).$(Rev:r)-${{parameters.selected_api_project}}"

stages:
- template: /pipelines/stage-templates/inject-parameters-for-${{parameters.selected_environment_set}}.yml
  parameters:
    template: /pipelines/stage-templates/export-api.yml
    parameters:
      commit_message: ${{parameters.commit_message}}
      selected_api_project: ${{parameters.selected_api_project}}
    selected_environment_set: ${{parameters.selected_environment_set}}