variables:
- group: 'Project Configuration'
- group: 'BUILD_instances' # If you want to use a variable group for connection details
- name: ClaimedResource
  value: ''

pool:
  name: '$(pool_name)'
  vmImage: '$(pool_image)'

stages:
- stage: ResourceManagement
  jobs:
  - job: ResourceManagementJob
    steps:
    - bash: |
        az extension add --name azure-devops

        # Define the name of the variable group containing resources
        variable_group_name="BUILD_instances"

        # Initialize variables
        selectedResource=""

        # Loop through available resources and claim the first one
        for i in {1..7}; do
          resource_variable="BUILD_0$i"
          az pipelines variable-group variable list --group-name "$variable_group_name" --name "$resource_variable" --org "$org_url" --project "$project_name"
          resource_status=$(az pipelines variable-group variable list --group-name "$variable_group_name" --name "$resource_variable" --org "$org_url" --project "$project_name" --query 'value' --output tsv)
          if [ "$resource_status" == "Available" ]; then
            # Claim the resource by updating its status
            az pipelines variable-group variable update --group-name "$variable_group_name" --name "$resource_variable" --new-value "Claimed" --org "$org_url" --project "$project_name"
            selectedResource="$resource_variable"
            break
          fi
        done

        if [ -z "$selectedResource" ]; then
          echo "No available resources found. Exiting..."
          exit 1
        fi

        echo "Selected Resource: $selectedResource"
        echo "##vso[task.setvariable variable=ClaimedResource]$selectedResource"
      displayName: 'Claim Resource'

    # Add steps to use and release the claimed resource

    - script: |
        # Use the claimed resource, e.g., in your build or deployment process
        echo "Using Claimed Resource: $(ClaimedResource)"
      displayName: 'Use Resource'

    - script: |
        # Release the claimed resource
        # Example: Release the claimed resource from the environment
        az pipelines resource release --name ResourcePoolEnvironment --type EnvironmentResource --identifier "$(ClaimedResource)"
        echo "Released Claimed Resource: $(ClaimedResource)"
      displayName: 'Release Resource'
