variables:
- group: 'Project Configuration'
- group: 'BUILD_instances' # If you want to use a variable group for connection details
- name: ClaimedResource
  value: ''

pool:
  name: '$(pool_name)'
  vmImage: '$(pool_image)'

stages:
- stage: ResourceManagement
  jobs:
  - job: ResourceManagementJob
    steps:
    - bash: |
        az extension add --name azure-devops
        echo DEBUG 01
        az pipelines variable-group list --organization https://dev.azure.com/pswm-inno-api-management --group-name BUILD_instances --query [0].id
        echo DEBUG 02
        group_id=$(az pipelines variable-group list --organization https://dev.azure.com/pswm-inno-api-management --group-name BUILD_instances --query [0].id)
        echo DEBUG 03

        resource_name="null"

        # Loop until a resource is available
        while [ "$resource_name" == "null" ]; do
          echo DEBUG 04
          az pipelines variable-group list --organization https://dev.azure.com/pswm-inno-api-management --group-name BUILD_instances --query [0].variables | jq "[ to_entries[] | select (.value.value==\"Available\") ][0]" 
          echo DEBUG 05
          resource_name=$(az pipelines variable-group list --organization https://dev.azure.com/pswm-inno-api-management --group-name BUILD_instances --query [0].variables | jq "[ to_entries[] | select (.value.value==\"Available\") ][0]")
          echo DEBUG 06

          if [ "$resource_name" == "null" ]; then
            echo "No available resource found. Waiting..."
            sleep 60
          fi
        done

        az pipelines variable-group variable update --organization https://dev.azure.com/pswm-inno-api-management --group-id $group_id --name $resource_name --value "Claimed by $(Build.BuildNumber)"

        echo "Selected Resource: $resource_name"
        echo "##vso[task.setvariable variable=ClaimedResource]$resource_name"
      displayName: 'Claim Resource'

    # Add steps to use and release the claimed resource

    - script: |
        # Use the claimed resource, e.g., in your build or deployment process
        echo "Using Claimed Resource: $(ClaimedResource)"
      displayName: 'Use Resource'

    - script: |
        # Release the claimed resource
        # Example: Release the claimed resource from the environment
        az pipelines resource release --name ResourcePoolEnvironment --type EnvironmentResource --identifier "$(ClaimedResource)"
        echo "Released Claimed Resource: $(ClaimedResource)"
      displayName: 'Release Resource'
