trigger: none

# resources:
#   pipelines:
#   - pipeline: trigger-pipeline-in-trigger-project # Name of the pipeline resource.
#     source: trigger-pipeline_URL # The name of the pipeline referenced by this pipeline resource.
#     project: trigger-project # Required only if the source pipeline is in another project
#     trigger: true

parameters:
- name: selected_environment_set
  displayName: Update API in which environment set?
  default: webm_io
  values:
  - webm_io
  - azure_demo_01
- name: api_id
  displayName: Update which API?
  type: string
  default: f3d2a3c1-0f83-43ab-a6ec-215b93e2ecf5
- name: update_url
  displayName: Update using which URL?
  type: string
  default: https://petstore.swagger.io/v2/swagger.json

stages:
- template: /pipelines/stage-templates/inject-parameters-for-${{parameters.selected_environment_set}}.yml
  parameters:
    template: /pipelines/stage-templates/update-api.yml
    parameters:
      api_id: ${{parameters.api_id}}
      update_type: "UpdateAPI_URL"
      update_url: ${{parameters.update_url}}
      update_username: $(update_username_petstore)
      update_password: $(update_password_petstore)
      update_file: ""
    selected_environment_set: ${{parameters.selected_environment_set}}